
const Corredor = {
  "Alça de Jeceaba" : "Alça de Jeceaba",
  "Córrego do Feijão" : "Córrego do Feijão",
  "Ferrovia do Aço" : "Ferrovia do Aço",
  "Linha do Centro" : "Linha do Centro",
  "Linha Rio - São Paulo" : "Linha Rio - São Paulo",
  "Linha Santos - Jundiaí" : "Linha Santos - Jundiaí",
  "Linha Tronco" : "Linha Tronco",
  "Ramal de Bias Fortes" : "Ramal de Bias Fortes",
  "Ramal de Conceiçãozinha" : "Ramal de Conceiçãozinha",
  "Ramal de Cosigua" : "Ramal de Cosigua",
  "Ramal de Mangaratiba" : "Ramal de Mangaratiba",
  "Ramal de Olhos D'Água" : "Ramal de Olhos D'Água",
  "Ramal de Perequê" : "Ramal de Perequê",
  "Ramal do Açominas" : "Ramal do Açominas",
  "Ramal do Arará" : "Ramal do Arará",
  "Ramal do Brisamar" : "Ramal do Brisamar",
  "Ramal do Paraopeba" : "Ramal do Paraopeba",
  "Ramal Paraibuna de Metais" : "Ramal Paraibuna de Metais",
  "Variante do Parateí" : "Variante do Parateí",
  "Variante Rio Grande da Serra - Suzano" : "Variante Rio Grande da Serra - Suzano"
};

const Patio = {
  "Açominas" :"Açominas",
  "Afonso Arinos " :"Afonso Arinos ",
  "Água Branca" :"Água Branca",
  "Agulhas Negras" :"Agulhas Negras",
  "Aiuruoca" :"Aiuruoca",
  "Alberto Flores" :"Alberto Flores",
  "Alça Dupla " :"Alça Dupla ",
  "Aliança" :"Aliança",
  "Aljezur" :"Aljezur",
  "Ambaí" :"Ambaí",
  "Andrade Pinto" :"Andrade Pinto",
  "Antonio Carlos" :"Antonio Carlos",
  "Aparecida" :"Aparecida",
  "Aracaré Leste" :"Aracaré Leste",
  "Arantina" :"Arantina",
  "Arará" :"Arará",
  "Areais" :"Areais",
  "Aristides Lobo" :"Aristides Lobo",
  "Arrojado Lisboa " :"Arrojado Lisboa ",
  "Baia Sepetiba" :"Baia Sepetiba",
  "Baltazar Fidelis" :"Baltazar Fidelis",
  "Barão de Angra" :"Barão de Angra",
  "Barão de Juparana" :"Barão de Juparana",
  "Barão de Vassouras" :"Barão de Vassouras",
  "Barbacena" :"Barbacena",
  "Bárbara" :"Bárbara",
  "Barnabé" :"Barnabé",
  "Barra do Piraí" :"Barra do Piraí",
  "Barra Funda" :"Barra Funda",
  "Barra Mansa" :"Barra Mansa",
  "Barreiro" :"Barreiro",
  "Barros Filho" :"Barros Filho",
  "Barroso" :"Barroso",
  "Belo Vale" :"Belo Vale",
  "Benfica" :"Benfica",
  "Bom Jardim" :"Bom Jardim",
  "Bom Jardim " :"Bom Jardim ",
  "Brás" :"Brás",
  "Brisamar" :"Brisamar",
  "Brumadinho" :"Brumadinho",
  "Buarque de Macedo" :"Buarque de Macedo",
  "Caburu" :"Caburu",
  "Caburu " :"Caburu ",
  "Caçapava" :"Caçapava",
  "Cachoeira" :"Cachoeira",
  "Cachoeira da Fumaça" :"Cachoeira da Fumaça",
  "Cachoeira Paulista" :"Cachoeira Paulista",
  "Caetano Lopes" :"Caetano Lopes",
  "Caieiras" :"Caieiras",
  "Calmon Viana" :"Calmon Viana",
  "Campestre" :"Campestre",
  "Campo Grande" :"Campo Grande",
  "Campo Limpo Paulista" :"Campo Limpo Paulista",
  "Capoeira Grande" :"Capoeira Grande",
  "Capuava" :"Capuava",
  "Carandaí" :"Carandaí",
  "Carlos Newlands" :"Carlos Newlands",
  "Carlos Niemeier" :"Carlos Niemeier",
  "Casal" :"Casal",
  "Casal Novo" :"Casal Novo",
  "Cedofeita" :"Cedofeita",
  "Chapeu D´uvas" :"Chapeu D´uvas",
  "Chapeu D'uvas" :"Chapeu D'uvas",
  "Chrockatt de Sá" :"Chrockatt de Sá",
  "Conceiçãozinha" :"Conceiçãozinha",
  "Condutor Castro" :"Condutor Castro",
  "Congonhas do Campo" :"Congonhas do Campo",
  "Congonhas do Campo " :"Congonhas do Campo ",
  "Conselheiro Lafaiete" :"Conselheiro Lafaiete",
  "Coroa Grande" :"Coroa Grande",
  "Coronel Araújo" :"Coronel Araújo",
  "Coronel Ermelino Matarazzo" :"Coronel Ermelino Matarazzo",
  "Coronel Eurico" :"Coronel Eurico",
  "Coronel João Carlos Guedes" :"Coronel João Carlos Guedes",
  "Coronel Xavier Chaves" :"Coronel Xavier Chaves",
  "Córrego do Feijão" :"Córrego do Feijão",
  "Córrego Serra" :"Córrego Serra",
  "Costa Barros" :"Costa Barros",
  "Cotegipe" :"Cotegipe",
  "Cruzeiro" :"Cruzeiro",
  "Cubatão" :"Cubatão",
  "Cubatão " :"Cubatão ",
  "Curuputuba" :"Curuputuba",
  "Del Castilho" :"Del Castilho",
  "Demétrio Ribeiro" :"Demétrio Ribeiro",
  "Deodoro" :"Deodoro",
  "Dias Tavares" :"Dias Tavares",
  "Doutor Joaquim Murtinho" :"Doutor Joaquim Murtinho",
  "Doutor Joaquim Murtinho " :"Doutor Joaquim Murtinho ",
  "Doutor Sá Fortes" :"Doutor Sá Fortes",
  "E.S. Gualberto" :"E.S. Gualberto",
  "Edmar Alves" :"Edmar Alves",
  "Engenheiro Cesar de Souza" :"Engenheiro Cesar de Souza",
  "Engenheiro Drumont" :"Engenheiro Drumont",
  "Engenheiro Eugênio de Melo" :"Engenheiro Eugênio de Melo",
  "Engenheiro Freixinho" :"Engenheiro Freixinho",
  "Engenheiro Gurgel" :"Engenheiro Gurgel",
  "Engenheiro Leonardo Mazziotti" :"Engenheiro Leonardo Mazziotti",
  "Engenheiro Martins Guimarães" :"Engenheiro Martins Guimarães",
  "Engenheiro Neiva" :"Engenheiro Neiva",
  "Engenheiro Passos" :"Engenheiro Passos",
  "Engenheiro Paulo de Frontin" :"Engenheiro Paulo de Frontin",
  "Engenheiro Pedro Paulo" :"Engenheiro Pedro Paulo",
  "Engenheiro São Paulo" :"Engenheiro São Paulo",
  "Engenheiro Simão Tamm" :"Engenheiro Simão Tamm",
  "Engenheiro Taulois" :"Engenheiro Taulois",
  "Engenheiro Vieira Cortez" :"Engenheiro Vieira Cortez",
  "Estação TUF" :"Estação TUF",
  "Ewbanck da Câmara" :"Ewbanck da Câmara",
  "Fernandes Pinheiro" :"Fernandes Pinheiro",
  "Ferrugem" :"Ferrugem",
  "Fim de Trecho" :"Fim de Trecho",
  "Fim do trecho" :"Fim do trecho",
  "Final do trecho" :"Final do trecho",
  "Final Ramal das Fábricas" :"Final Ramal das Fábricas",
  "Floriano" :"Floriano",
  "Francisco Bernardino" :"Francisco Bernardino",
  "Francisco Morato" :"Francisco Morato",
  "Franco da Rocha" :"Franco da Rocha",
  "Furnas" :"Furnas",
  "Gaje" :"Gaje",
  "General Dorival de Brito" :"General Dorival de Brito",
  "Guaíba" :"Guaíba",
  "Guandú" :"Guandú",
  "Guapituba" :"Guapituba",
  "Guararema" :"Guararema",
  "Guaratinguetá" :"Guaratinguetá",
  "Herculano Pena" :"Herculano Pena",
  "Heredia de Sá" :"Heredia de Sá",
  "Honório Gurgel" :"Honório Gurgel",
  "Humberto Antunes" :"Humberto Antunes",
  "Ibicuí" :"Ibicuí",
  "Ibirité" :"Ibirité",
  "Ilídio" :"Ilídio",
  "Inconfidentes" :"Inconfidentes",
  "Inferno Verde" :"Inferno Verde",
  "Ipiranga" :"Ipiranga",
  "Itabirito" :"Itabirito",
  "Itacuruçá" :"Itacuruçá",
  "Itaguaí" :"Itaguaí",
  "Itapeti" :"Itapeti",
  "Itaquaquecetuba" :"Itaquaquecetuba",
  "Itatiaia" :"Itatiaia",
  "Itutinga" :"Itutinga",
  "Jacutinga" :"Jacutinga",
  "Japeri" :"Japeri",
  "Jaraguá" :"Jaraguá",
  "Jatobá" :"Jatobá",
  "Jeceaba" :"Jeceaba",
  "Jeceaba " :"Jeceaba ",
  "João Aires" :"João Aires",
  "Joaquim Reis" :"Joaquim Reis",
  "Juiz de Fora" :"Juiz de Fora",
  "KM 10" :"KM 10",
  "KM 110" :"KM 110",
  "KM 5" :"KM 5",
  "KM 6" :"KM 6",
  "KM 7" :"KM 7",
  "KM 8" :"KM 8",
  "KM 9" :"KM 9",
  "Lagoa dos Porcos" :"Lagoa dos Porcos",
  "Lapa" :"Lapa",
  "Lobo Leite" :"Lobo Leite",
  "Lorena" :"Lorena",
  "Luz" :"Luz",
  "Madre de Deus" :"Madre de Deus",
  "Manoel Feio" :"Manoel Feio",
  "Mantiqueira" :"Mantiqueira",
  "Mariano Procópio" :"Mariano Procópio",
  "Mariano Procópio " :"Mariano Procópio ",
  "Marinhos" :"Marinhos",
  "Marinhos " :"Marinhos ",
  "Mário Belo" :"Mário Belo",
  "Mário Campos" :"Mário Campos",
  "Mário Campos " :"Mário Campos ",
  "Mário Castilho" :"Mário Castilho",
  "Martins Costa" :"Martins Costa",
  "Matias Barbosa" :"Matias Barbosa",
  "Mauá" :"Mauá",
  "Melo Franco" :"Melo Franco",
  "Mendes" :"Mendes",
  "Miguel Burnier" :"Miguel Burnier",
  "Moeda" :"Moeda",
  "Mogi das Cruzes" :"Mogi das Cruzes",
  "Mooca" :"Mooca",
  "Morsing" :"Morsing",
  "Olhos D'Água" :"Olhos D'Água",
  "Otavio Dapieve" :"Otavio Dapieve",
  "Ouro Fino" :"Ouro Fino",
  "Ouro Fino " :"Ouro Fino ",
  "Pagador Andrade" :"Pagador Andrade",
  "Palmeira da Serra" :"Palmeira da Serra",
  "Paraíba do Sul" :"Paraíba do Sul",
  "Paraibuna " :"Paraibuna ",
  "Paraibuna de Metais" :"Paraibuna de Metais",
  "Paraibuna Novo" :"Paraibuna Novo",
  "Paranapiacaba" :"Paranapiacaba",
  "Pari" :"Pari",
  "Pedra do Sino" :"Pedra do Sino",
  "Pedreira de Carandaí" :"Pedreira de Carandaí",
  "Perus" :"Perus",
  "Piaçaguera" :"Piaçaguera",
  "Pindamonhangaba" :"Pindamonhangaba",
  "Pinheiral" :"Pinheiral",
  "Pinheirinho" :"Pinheirinho",
  "Piqueri" :"Piqueri",
  "Pires" :"Pires",
  "Pirituba" :"Pirituba",
  "Pitangueiras" :"Pitangueiras",
  "Pombal" :"Pombal",
  "Pombal " :"Pombal ",
  "Porto Real" :"Porto Real",
  "Posto Alfa" :"Posto Alfa",
  "Posto Elisson" :"Posto Elisson",
  "Posto Falcão" :"Posto Falcão",
  "Posto KM 194" :"Posto KM 194",
  "Posto KM 195" :"Posto KM 195",
  "Posto KM 196" :"Posto KM 196",
  "Posto KM 197" :"Posto KM 197",
  "Posto KM 198" :"Posto KM 198",
  "Posto KM 232" :"Posto KM 232",
  "Posto KM 250" :"Posto KM 250",
  "Posto KM 261" :"Posto KM 261",
  "Posto KM 271" :"Posto KM 271",
  "Posto KM 298" :"Posto KM 298",
  "Posto KM 315" :"Posto KM 315",
  "Posto KM 373" :"Posto KM 373",
  "Posto km 374" :"Posto km 374",
  "Posto km 375" :"Posto km 375",
  "Posto km 44" :"Posto km 44",
  "Posto KM 452" :"Posto KM 452",
  "Posto KM 460" :"Posto KM 460",
  "Posto KM 482" :"Posto KM 482",
  "Posto KM 490" :"Posto KM 490",
  "Posto KM 520" :"Posto KM 520",
  "Posto KM 537" :"Posto KM 537",
  "Posto KM 575" :"Posto KM 575",
  "Posto KM 576" :"Posto KM 576",
  "Posto KM 577" :"Posto KM 577",
  "Posto KM 578" :"Posto KM 578",
  "Posto KM 579" :"Posto KM 579",
  "Posto KM 580" :"Posto KM 580",
  "Posto KM 581" :"Posto KM 581",
  "Posto KM 582" :"Posto KM 582",
  "Posto KM 583" :"Posto KM 583",
  "Posto KM 584" :"Posto KM 584",
  "Posto KM 585" :"Posto KM 585",
  "Posto KM 586" :"Posto KM 586",
  "Posto KM 587" :"Posto KM 587",
  "Posto KM 588" :"Posto KM 588",
  "Posto KM 589" :"Posto KM 589",
  "Posto KM 63" :"Posto KM 63",
  "Posto KM 64" :"Posto KM 64",
  "Posto Km 65" :"Posto Km 65",
  "Posto KM315" :"Posto KM315",
  "Prefeito Saladino" :"Prefeito Saladino",
  "Pulverização" :"Pulverização",
  "Queluz" :"Queluz",
  "Rademaker" :"Rademaker",
  "Raiz da Serra" :"Raiz da Serra",
  "Recenvindo" :"Recenvindo",
  "Remédios" :"Remédios",
  "Resende Costa" :"Resende Costa",
  "Retiro" :"Retiro",
  "Ribeirão Pires" :"Ribeirão Pires",
  "Rio Grande da Serra" :"Rio Grande da Serra",
  "Rio Preto" :"Rio Preto",
  "Rio Santana" :"Rio Santana",
  "Rio Vermelho" :"Rio Vermelho",
  "Rio Vermelho " :"Rio Vermelho ",
  "Rocha Dias" :"Rocha Dias",
  "Rocha Miranda" :"Rocha Miranda",
  "Rocha Sobrinho" :"Rocha Sobrinho",
  "Roseira" :"Roseira",
  "Saí" :"Saí",
  "Samora Machel" :"Samora Machel",
  "Santa Rosa" :"Santa Rosa",
  "Santa Rosa " :"Santa Rosa ",
  "Santana da Barra" :"Santana da Barra",
  "Santo André" :"Santo André",
  "Santos" :"Santos",
  "Santos Dumont" :"Santos Dumont",
  "São Bento" :"São Bento",
  "São Caetano do Sul" :"São Caetano do Sul",
  "São Gonçalo do Bação" :"São Gonçalo do Bação",
  "São Joaquim" :"São Joaquim",
  "São José dos Campos" :"São José dos Campos",
  "São Matheus" :"São Matheus",
  "São Silvestre " :"São Silvestre ",
  "Sarzedo" :"Sarzedo",
  "Sarzedo Novo " :"Sarzedo Novo ",
  "Saudade" :"Saudade",
  "Sebastião Lacerda" :"Sebastião Lacerda",
  "Serraria" :"Serraria",
  "Sobragi" :"Sobragi",
  "Sobragi " :"Sobragi ",
  "Souza Aguiar" :"Souza Aguiar",
  "Suzano" :"Suzano",
  "Suzano " :"Suzano ",
  "Suzano Novo" :"Suzano Novo",
  "Tamanduateí" :"Tamanduateí",
  "Taubaté" :"Taubaté",
  "Terminal Cimento Barroso" :"Terminal Cimento Barroso",
  "Três Rios" :"Três Rios",
  "Utinga" :"Utinga",
  "Vargem Alegre" :"Vargem Alegre",
  "Várzea Paulista" :"Várzea Paulista",
  "Viga" :"Viga",
  "Vila Clarice" :"Vila Clarice",
  "Vila Muriqui" :"Vila Muriqui",
  "Vila Queimada" :"Vila Queimada",
  "Volta Redonda" :"Volta Redonda",
  "Waldemar de Brito" :"Waldemar de Brito",

}



const columnsVPF = [
  {
    field: "BP", title: "Ficha",
    cellStyle: {
      width: 5,
      maxWidth: 5
    },
  },
  {
    field: "Versao", title: "Versão",
    cellStyle: {
      width: 5,
      maxWidth: 5
    },
    headerStyle: {
      width: 5,
      maxWidth: 5
    }
  },
  { field: "Corredor", title: "Corredor", lookup: Corredor,
    cellStyle: {
      width: 50,
      maxWidth: 50
    },
    headerStyle: {
      width: 50,
      maxWidth: 50
    }
  },
  { field: "SiglaPatio", title: "Pátio Anterior", lookup: Patio},
  { field: "SiglaPatioPrx", title: "Pátio Posterior", lookup: Patio, hidden:true, hiddenByColumnsButton: true },
  { field: "PosicaoKmIni",
    title: "Km Inicial",
  },
  { field: "DistBoletoExtIniInvasao", title: "Boleto (<)",
    customFilterAndSearch: (term, rowData) => term >= rowData.DistBoletoExtIniInvasao
  },
  {
    field: "InicioValidade", title: "Inicio Validade", type: 'date',
    cellStyle: {
      width: 15,
      maxWidth: 15
    },
  },
];

const localization = {
  header: {
    actions: 'Ações'
  },
  toolbar: {
    searchTooltip: 'Pesquisar',
    searchPlaceholder: 'Pesquisar',
    exportTitle: 'Exportar',
    showColumnsTitle: 'Adiciona ou remove colunas',
  },
  pagination: {
    labelRowsSelect: 'linhas',
    labelDisplayedRows: 'Total:{count} / Mostrando: {from}-{to}',
    firstTooltip: 'Primeira página',
    previousTooltip: 'Página anterior',
    nextTooltip: 'Próxima página',
    lastTooltip: 'Última página'
  },
};

const options = {
  exportButton: true,
  exportAllData: true,
  filtering: true,
  pageSize: 8,
  pageSizeOptions: [8, 10, 20, 50],
  padding: 'dense',
  columnsButton: true,
  search: false,
  // selection: true,
  loadingType: 'linear'
};

const styles = {
  iconTable: {
    fill: '#64b5f6',
    width: '28',
    height: '28',
    marginLeft: '5',
  },
  iconTableDisabled: {
    fill: '#bdbdbd',
    width: '28',
    height: '28',
    marginLeft: '5'
  },
  iconAdd: {
    fill: '#0072ea',
    marginTop: '10',
    width: '24',
    height: '24',
  },
  filterFormControl: {
    display: 'flex',
    marginLeft: 10,
    marginTop: 5,
  },
  filterSelect: {
    width: 200,
    marginBottom: 10,
    marginRight: 10,
  },
};

module.exports = {
  columnsVPF,
  localization,
  options,
  styles,
};
