const TPRVI = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const CONSV = [ { "label": "Bom", "value": "Bom" }, { "label": "Fora do Escopo", "value": "Fora do Escopo" }, { "label": "Não existe", "value": "Não existe" }, { "label": "Não Informado", "value": "Não Informado" }, { "label": "Não se aplica", "value": "Não se aplica" }, { "label": "Recuperável", "value": "Recuperável" }, { "label": "Regular", "value": "Regular" }, { "label": "Ruim", "value": "Ruim" }, { "label": "Sucateado", "value": "Sucateado" } ];

const TIUTI = [ { "label": "Desocupado", "value": "Desocupado" }, { "label": "Não se Aplica", "value": "Não se Aplica" }, { "label": "Terceiros", "value": "Terceiros" }, { "label": "Terceiros - Prefeitura", "value": "Terceiros - Prefeitura" }, { "label": "VLI", "value": "VLI" } ];

const TRCHO = [ { "label": "ARACAJU - PROPRIA", "value": "ARACAJU - PROPRIA" }, { "label": "ARAGUARI - GOIANDIRA", "value": "ARAGUARI - GOIANDIRA" }, { "label": "ARATU - MAPELE", "value": "ARATU - MAPELE" }, { "label": "AZURITA - DIVINOPOLIS", "value": "AZURITA - DIVINOPOLIS" }, { "label": "BARRA MANSA - ANGRA DOS REIS", "value": "BARRA MANSA - ANGRA DOS REIS" }, { "label": "BELO HORIZONTE (E) - HORTO FLORESTAL (I)", "value": "BELO HORIZONTE (E) - HORTO FLORESTAL (I)" }, { "label": "CACH.DO ITAPEMIRIM - FABRICA DE CIMENTO", "value": "CACH.DO ITAPEMIRIM - FABRICA DE CIMENTO" }, { "label": "CACH.DO ITAPEMIRIM - VITORIA", "value": "CACH.DO ITAPEMIRIM - VITORIA" }, { "label": "CALAFATE - FERRUGEM", "value": "CALAFATE - FERRUGEM" }, { "label": "CAMPOS - CISNEIRO", "value": "CAMPOS - CISNEIRO" }, { "label": "CAMPOS - MACAE", "value": "CAMPOS - MACAE" }, { "label": "CAMPOS - MURUNDU", "value": "CAMPOS - MURUNDU" }, { "label": "CAPITAO EDUARDO - MATOSINHOS", "value": "CAPITAO EDUARDO - MATOSINHOS" }, { "label": "CATIBOABA - LICINIO DE ALMEIDA", "value": "CATIBOABA - LICINIO DE ALMEIDA" }, { "label": "CONCEICAO DE FEIRA - IACU", "value": "CONCEICAO DE FEIRA - IACU" }, { "label": "CORINTO - BURITIZEIRO", "value": "CORINTO - BURITIZEIRO" }, { "label": "CORINTO - MONTES CLAROS", "value": "CORINTO - MONTES CLAROS" }, { "label": "DIVINOPOLIS - EYA-POSTO KM 298", "value": "DIVINOPOLIS - EYA-POSTO KM 298" }, { "label": "DIVINOPOLIS - GARCAS DE MINAS", "value": "DIVINOPOLIS - GARCAS DE MINAS" }, { "label": "ELDORADO - POSTO TELEGRAFICO", "value": "ELDORADO - POSTO TELEGRAFICO" }, { "label": "ENG BHERING - GARCAS DE MINAS", "value": "ENG BHERING - GARCAS DE MINAS" }, { "label": "ENG BHERING - RUTILO", "value": "ENG BHERING - RUTILO" }, { "label": "ENG BHERING - TRES CORACOES", "value": "ENG BHERING - TRES CORACOES" }, { "label": "ENG.BHERING - EYA-POSTO KM 298", "value": "ENG.BHERING - EYA-POSTO KM 298" }, { "label": "ESPERANÇA (E) - MIGUEL BURNIER (I)", "value": "ESPERANÇA (E) - MIGUEL BURNIER (I)" }, { "label": "FERROBAN", "value": "FERROBAN" }, { "label": "FERRUGEM - ELDORADO", "value": "FERRUGEM - ELDORADO" }, { "label": "GARCAS MINAS - IBIA", "value": "GARCAS MINAS - IBIA" }, { "label": "GENERAL CARNEIRO - SABARA", "value": "GENERAL CARNEIRO - SABARA" }, { "label": "GOIANDIRA - RONCADOR NOVO", "value": "GOIANDIRA - RONCADOR NOVO" }, { "label": "IACU - QUEIMADINHAS", "value": "IACU - QUEIMADINHAS" }, { "label": "IBIA - AMOROSO COSTA", "value": "IBIA - AMOROSO COSTA" }, { "label": "IBIA - GOIANDIRA", "value": "IBIA - GOIANDIRA" }, { "label": "JAPERI - ENG. PEDREIRA", "value": "JAPERI - ENG. PEDREIRA" }, { "label": "JARINA - ENG CASTILHO", "value": "JARINA - ENG CASTILHO" }, { "label": "JARINA - GOIANIA", "value": "JARINA - GOIANIA" }, { "label": "LICINIO DE ALMEIDA - MONTE AZUL", "value": "LICINIO DE ALMEIDA - MONTE AZUL" }, { "label": "LIGACAO - PONTE NOVA", "value": "LIGACAO - PONTE NOVA" }, { "label": "MACAE - VISCONDE DE ITABORAI", "value": "MACAE - VISCONDE DE ITABORAI" }, { "label": "MAPELE - CONCEICAO DE FEIRA", "value": "MAPELE - CONCEICAO DE FEIRA" }, { "label": "MAPELE - SAO FRANCISCO", "value": "MAPELE - SAO FRANCISCO" }, { "label": "MARIANA - MIGUEL BURNIER", "value": "MARIANA - MIGUEL BURNIER" }, { "label": "MATOSINHOS - CORINTO", "value": "MATOSINHOS - CORINTO" }, { "label": "MONTES CLAROS - MONTE AZUL", "value": "MONTES CLAROS - MONTE AZUL" }, { "label": "MURUNDU - CACH.DO ITAPEMIRIM", "value": "MURUNDU - CACH.DO ITAPEMIRIM" }, { "label": "PARAÍBA DO SUL (E) - JAPERI (E)", "value": "PARAÍBA DO SUL (E) - JAPERI (E)" }, { "label": "PATROCINIO - ARAGUARI", "value": "PATROCINIO - ARAGUARI" }, { "label": "PONTE NOVA - MARIANA", "value": "PONTE NOVA - MARIANA" }, { "label": "PORTO NOVO - RECREIO", "value": "PORTO NOVO - RECREIO" }, { "label": "POSTO TELEGRAFICO - AZURITA", "value": "POSTO TELEGRAFICO - AZURITA" }, { "label": "QUEIMADAS - SENHOR DO BONFIM", "value": "QUEIMADAS - SENHOR DO BONFIM" }, { "label": "QUEIMADINHAS - TANHACU", "value": "QUEIMADINHAS - TANHACU" }, { "label": "RECREIO - LIGACAO", "value": "RECREIO - LIGACAO" }, { "label": "RIO REAL - ARACAJU", "value": "RIO REAL - ARACAJU" }, { "label": "RONCADOR NOVO - BRASILIA", "value": "RONCADOR NOVO - BRASILIA" }, { "label": "RONCADOR NOVO - JARINA", "value": "RONCADOR NOVO - JARINA" }, { "label": "RUTILO - BARRA MANSA", "value": "RUTILO - BARRA MANSA" }, { "label": "SABARA - ESPERANCA", "value": "SABARA - ESPERANCA" }, { "label": "SALVADOR - ARATU", "value": "SALVADOR - ARATU" }, { "label": "SAO FRANCISCO - RIO REAL", "value": "SAO FRANCISCO - RIO REAL" }, { "label": "SAO FRANCISCO - SERRINHA", "value": "SAO FRANCISCO - SERRINHA" }, { "label": "SENHOR DO BONFIM - ANTONIO GONCALVES", "value": "SENHOR DO BONFIM - ANTONIO GONCALVES" }, { "label": "SENHOR DO BONFIM - PETROLINA", "value": "SENHOR DO BONFIM - PETROLINA" }, { "label": "SERRINHA - QUEIMADAS", "value": "SERRINHA - QUEIMADAS" }, { "label": "TANHACU - CATIBOABA", "value": "TANHACU - CATIBOABA" }, { "label": "TRES CORACOES - VARGINHA", "value": "TRES CORACOES - VARGINHA" }, { "label": "TRES RIOS - PORTO NOVO", "value": "TRES RIOS - PORTO NOVO" } ];

const COMPN = [ { "label": "VLI", "value": "VLI" } ];

const XANEST = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const PMTDT = [ { "label": "Fora de escopo", "value": "Fora de escopo" }, { "label": "Linha", "value": "Linha" }, { "label": "Não Informado", "value": "Não Informado" }, { "label": "Terreno", "value": "Terreno" } ];

const TPOCT = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const XANRVI = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const TPRVE = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const STOPR = [{ "value": "Em Operação", "label": "Em Operação" }, { "value": "Imobilizado", "label": "Imobilizado" }];

const XANESQ = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const XANSTE = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const CDCRR = [
  { "label": "Alça de Jeceaba" , "value": "Alça de Jeceaba" },
  { "label": "Córrego do Feijão" , "value": "Córrego do Feijão" },
  { "label": "Ferrovia do Aço" , "value": "Ferrovia do Aço" },
  { "label": "Linha do Centro" , "value": "Linha do Centro" },
  { "label": "Linha Rio - São Paulo" , "value": "Linha Rio - São Paulo" },
  { "label": "Linha Santos - Jundiaí" , "value": "Linha Santos - Jundiaí" },
  { "label": "Linha Tronco" , "value": "Linha Tronco" },
  { "label": "Ramal de Bias Fortes" , "value": "Ramal de Bias Fortes" },
  { "label": "Ramal de Conceiçãozinha" , "value": "Ramal de Conceiçãozinha" },
  { "label": "Ramal de Cosigua" , "value": "Ramal de Cosigua" },
  { "label": "Ramal de Mangaratiba" , "value": "Ramal de Mangaratiba" },
  { "label": "Ramal de Olhos D'Água" , "value": "Ramal de Olhos D'Água" },
  { "label": "Ramal de Perequê" , "value": "Ramal de Perequê" },
  { "label": "Ramal do Açominas" , "value": "Ramal do Açominas" },
  { "label": "Ramal do Arará" , "value": "Ramal do Arará" },
  { "label": "Ramal do Brisamar" , "value": "Ramal do Brisamar" },
  { "label": "Ramal do Paraopeba" , "value": "Ramal do Paraopeba" },
  { "label": "Ramal Paraibuna de Metais" , "value": "Ramal Paraibuna de Metais" },
  { "label": "Variante do Parateí" , "value": "Variante do Parateí" },
  { "label": "Variante Rio Grande da Serra - Suzano" , "value": "Variante Rio Grande da Serra - Suzano" },
 ];

const XTPSTA = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const TPESG = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const CONSG = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const EDPDC = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const CDLMR = [ { "label": "Entre Água da Prata e Bauxita", "value": "Entre Água da Prata e Bauxita" }, { "label": "Entre Alagoinhas e Porto Aratu", "value": "Entre Alagoinhas e Porto Aratu" }, { "label": "Entre Couto e Silva", "value": "Entre Couto e Silva" }, { "label": "Entre Itabaianinha e Aracajú", "value": "Entre Itabaianinha e Aracajú" }, { "label": "Entre Silva e Oliveira", "value": "Entre Silva e Oliveira" }, { "label": "Pátio ADM", "value": "Pátio ADM" }, { "label": "Pátio Aguaí", "value": "Pátio Aguaí" }, { "label": "Pátio Águas da Prata", "value": "Pátio Águas da Prata" }, { "label": "Pátio Alagoinhas", "value": "Pátio Alagoinhas" }, { "label": "Pátio Além Paraíba", "value": "Pátio Além Paraíba" }, { "label": "Pátio Almeida Campos", "value": "Pátio Almeida Campos" }, { "label": "Pátio Amadeu Lacerda", "value": "Pátio Amadeu Lacerda" }, { "label": "Pátio Angicos", "value": "Pátio Angicos" }, { "label": "Pátio Angra dos Reis", "value": "Pátio Angra dos Reis" }, { "label": "Pátio Anísio Brás", "value": "Pátio Anísio Brás" }, { "label": "Pátio Aracajú", "value": "Pátio Aracajú" }, { "label": "Pátio Araguari", "value": "Pátio Araguari" }, { "label": "Pátio Aramari", "value": "Pátio Aramari" }, { "label": "Pátio Arantina", "value": "Pátio Arantina" }, { "label": "Pátio Araxá", "value": "Pátio Araxá" }, { "label": "Pátio Arcos", "value": "Pátio Arcos" }, { "label": "Pátio Argolas", "value": "Pátio Argolas" }, { "label": "Pátio Aroaba", "value": "Pátio Aroaba" }, { "label": "Pátio Augusto Pestana", "value": "Pátio Augusto Pestana" }, { "label": "Pátio Azurita", "value": "Pátio Azurita" }, { "label": "Pátio Barão de Camargo", "value": "Pátio Barão de Camargo" }, { "label": "Pátio Barra Mansa", "value": "Pátio Barra Mansa" }, { "label": "Pátio Batista Almeida", "value": "Pátio Batista Almeida" }, { "label": "Pátio Batista Frazão", "value": "Pátio Batista Frazão" }, { "label": "Pátio Batuíra", "value": "Pátio Batuíra" }, { "label": "Pátio Belo Horizonte", "value": "Pátio Belo Horizonte" }, { "label": "Pátio Betim", "value": "Pátio Betim" }, { "label": "Pátio Boa Vista", "value": "Pátio Boa Vista" }, { "label": "Pátio Boa Vista Nova", "value": "Pátio Boa Vista Nova" }, { "label": "Pátio Bocaina", "value": "Pátio Bocaina" }, { "label": "Pátio Bom Sucesso", "value": "Pátio Bom Sucesso" }, { "label": "Pátio Brasília", "value": "Pátio Brasília" }, { "label": "Pátio Brejo Alegre", "value": "Pátio Brejo Alegre" }, { "label": "Pátio Brumado", "value": "Pátio Brumado" }, { "label": "Pátio Bugios", "value": "Pátio Bugios" }, { "label": "Pátio Calambau", "value": "Pátio Calambau" }, { "label": "Pátio Calcário", "value": "Pátio Calcário" }, { "label": "Pátio Calcário (Barra Mansa)", "value": "Pátio Calcário (Barra Mansa)" }, { "label": "Pátio Calsete", "value": "Pátio Calsete" }, { "label": "Pátio Campo Belo", "value": "Pátio Campo Belo" }, { "label": "Pátio Campos", "value": "Pátio Campos" }, { "label": "Pátio Campos dos Goytacazes", "value": "Pátio Campos dos Goytacazes" }, { "label": "Pátio Capitão Eduardo", "value": "Pátio Capitão Eduardo" }, { "label": "Pátio Carapebus", "value": "Pátio Carapebus" }, { "label": "Pátio Cariacica", "value": "Pátio Cariacica" }, { "label": "Pátio Carmo da Mata", "value": "Pátio Carmo da Mata" }, { "label": "Pátio Carmo do Cajuru", "value": "Pátio Carmo do Cajuru" }, { "label": "Pátio Carrancas", "value": "Pátio Carrancas" }, { "label": "Pátio Carreira Comprida", "value": "Pátio Carreira Comprida" }, { "label": "Pátio Carvão", "value": "Pátio Carvão" }, { "label": "Pátio Casa Branca", "value": "Pátio Casa Branca" }, { "label": "Pátio Casimiro de Abreu", "value": "Pátio Casimiro de Abreu" }, { "label": "Pátio Cataguases", "value": "Pátio Cataguases" }, { "label": "Pátio Catiara", "value": "Pátio Catiara" }, { "label": "Pátio Catiboaba", "value": "Pátio Catiboaba" }, { "label": "Pátio Cel. Perreira Lima", "value": "Pátio Cel. Perreira Lima" }, { "label": "Pátio Cenibra", "value": "Pátio Cenibra" }, { "label": "Pátio Cimbasa", "value": "Pátio Cimbasa" }, { "label": "Pátio Cimento Nassau", "value": "Pátio Cimento Nassau" }, { "label": "Pátio CNAGA", "value": "Pátio CNAGA" }, { "label": "Pátio Colatina", "value": "Pátio Colatina" }, { "label": "Pátio Conceição da Feira", "value": "Pátio Conceição da Feira" }, { "label": "Pátio Contendas", "value": "Pátio Contendas" }, { "label": "Pátio Copec", "value": "Pátio Copec" }, { "label": "Pátio Corinto", "value": "Pátio Corinto" }, { "label": "Pátio Costa Lacerda", "value": "Pátio Costa Lacerda" }, { "label": "Pátio Coti", "value": "Pátio Coti" }, { "label": "Pátio Couto e Silva", "value": "Pátio Couto e Silva" }, { "label": "Pátio Cravinhos", "value": "Pátio Cravinhos" }, { "label": "Pátio Curvelo", "value": "Pátio Curvelo" }, { "label": "Pátio de Cariacica", "value": "Pátio de Cariacica" }, { "label": "Pátio de Ibiá", "value": "Pátio de Ibiá" }, { "label": "Pátio Desembargador Drumont", "value": "Pátio Desembargador Drumont" }, { "label": "Pátio Divinópolis", "value": "Pátio Divinópolis" }, { "label": "Pátio Djalma Dutra", "value": "Pátio Djalma Dutra" }, { "label": "Pátio DNIT", "value": "Pátio DNIT" }, { "label": "Pátio Dr. Lund", "value": "Pátio Dr. Lund" }, { "label": "Pátio Eldorado", "value": "Pátio Eldorado" }, { "label": "Pátio Eldorado / Capitão Eduardo", "value": "Pátio Eldorado / Capitão Eduardo" }, { "label": "Pátio Embiruçu", "value": "Pátio Embiruçu" }, { "label": "Pátio Eng. Bandeira", "value": "Pátio Eng. Bandeira" }, { "label": "Pátio Eng. Dolabela", "value": "Pátio Eng. Dolabela" }, { "label": "Pátio Eng. Hélio Martins", "value": "Pátio Eng. Hélio Martins" }, { "label": "Pátio Eng. Navarro", "value": "Pátio Eng. Navarro" }, { "label": "Pátio Engenheiro Adelmar", "value": "Pátio Engenheiro Adelmar" }, { "label": "Pátio Engenheiro Bhering", "value": "Pátio Engenheiro Bhering" }, { "label": "Pátio Engenheiro Dolabela", "value": "Pátio Engenheiro Dolabela" }, { "label": "Pátio Engenheiro Gordilho", "value": "Pátio Engenheiro Gordilho" }, { "label": "Pátio Engenheiro Hélio Martins", "value": "Pátio Engenheiro Hélio Martins" }, { "label": "Pátio Espinosa", "value": "Pátio Espinosa" }, { "label": "Pátio Esplanada", "value": "Pátio Esplanada" }, { "label": "Pátio Estação Velha de Araguari", "value": "Pátio Estação Velha de Araguari" }, { "label": "Pátio Estevão Lobo", "value": "Pátio Estevão Lobo" }, { "label": "Pátio Evangelina", "value": "Pátio Evangelina" }, { "label": "Pátio Fábrica de Cimento", "value": "Pátio Fábrica de Cimento" }, { "label": "Pátio Faria", "value": "Pátio Faria" }, { "label": "Pátio Fazendão", "value": "Pátio Fazendão" }, { "label": "Pátio Folhados", "value": "Pátio Folhados" }, { "label": "Pátio Formiga", "value": "Pátio Formiga" }, { "label": "Pátio Francisco Braz", "value": "Pátio Francisco Braz" }, { "label": "Pátio Francisco Braz a Amadeu Lacerda", "value": "Pátio Francisco Braz a Amadeu Lacerda" }, { "label": "Pátio Franklin Sampaio", "value": "Pátio Franklin Sampaio" }, { "label": "Pátio Frederico Sellow", "value": "Pátio Frederico Sellow" }, { "label": "Pátio Garças de Minas", "value": "Pátio Garças de Minas" }, { "label": "Pátio Goiandira", "value": "Pátio Goiandira" }, { "label": "Pátio Gonçalves Ferreira", "value": "Pátio Gonçalves Ferreira" }, { "label": "Pátio Governador Portela", "value": "Pátio Governador Portela" }, { "label": "Pátio Governador Valadares", "value": "Pátio Governador Valadares" }, { "label": "Pátio Hélio Torres", "value": "Pátio Hélio Torres" }, { "label": "Pátio Horto Florestal", "value": "Pátio Horto Florestal" }, { "label": "Pátio Iaçu", "value": "Pátio Iaçu" }, { "label": "Pátio Iaçú", "value": "Pátio Iaçú" }, { "label": "Pátio Ibiá", "value": "Pátio Ibiá" }, { "label": "Pátio Ibitiruí", "value": "Pátio Ibitiruí" }, { "label": "Pátio Inspetor Quirino", "value": "Pátio Inspetor Quirino" }, { "label": "Pátio Intendente Câmara", "value": "Pátio Intendente Câmara" }, { "label": "Pátio Ipameri", "value": "Pátio Ipameri" }, { "label": "Pátio Ipatinga", "value": "Pátio Ipatinga" }, { "label": "Pátio Itacibá", "value": "Pátio Itacibá" }, { "label": "Pátio Itamarati", "value": "Pátio Itamarati" }, { "label": "Pátio Itiúba", "value": "Pátio Itiúba" }, { "label": "Pátio Itumirim", "value": "Pátio Itumirim" }, { "label": "Pátio Ituverava", "value": "Pátio Ituverava" }, { "label": "Pátio Jacarandá", "value": "Pátio Jacarandá" }, { "label": "Pátio Jaguariúna", "value": "Pátio Jaguariúna" }, { "label": "Pátio Janaúba", "value": "Pátio Janaúba" }, { "label": "Pátio Jardim do Ingá", "value": "Pátio Jardim do Ingá" }, { "label": "Pátio Joaquim Felicio", "value": "Pátio Joaquim Felicio" }, { "label": "Pátio Joatuba", "value": "Pátio Joatuba" }, { "label": "Pátio José Bittencourt", "value": "Pátio José Bittencourt" }, { "label": "Pátio Lagoa da Prata", "value": "Pátio Lagoa da Prata" }, { "label": "Pátio Lagoa Redonda", "value": "Pátio Lagoa Redonda" }, { "label": "Pátio Lamarão", "value": "Pátio Lamarão" }, { "label": "Pátio Lameirão", "value": "Pátio Lameirão" }, { "label": "Pátio Laranjeira", "value": "Pátio Laranjeira" }, { "label": "Pátio Lavras", "value": "Pátio Lavras" }, { "label": "Pátio Leopoldo Bulhões", "value": "Pátio Leopoldo Bulhões" }, { "label": "Pátio Licínio de Almeida", "value": "Pátio Licínio de Almeida" }, { "label": "Pátio Lídice", "value": "Pátio Lídice" }, { "label": "Pátio Macaé", "value": "Pátio Macaé" }, { "label": "Pátio Macaia", "value": "Pátio Macaia" }, { "label": "Pátio Majita", "value": "Pátio Majita" }, { "label": "Pátio Marechal Floriano", "value": "Pátio Marechal Floriano" }, { "label": "Pátio Mariana", "value": "Pátio Mariana" }, { "label": "Pátio Matheus Leme Novo", "value": "Pátio Matheus Leme Novo" }, { "label": "Pátio Mato Seco", "value": "Pátio Mato Seco" }, { "label": "Pátio Matozinhos", "value": "Pátio Matozinhos" }, { "label": "Pátio Messias Lopes", "value": "Pátio Messias Lopes" }, { "label": "Pátio Mimoso do Sul", "value": "Pátio Mimoso do Sul" }, { "label": "Pátio Mogi-Guaçu", "value": "Pátio Mogi-Guaçu" }, { "label": "Pátio Monte Azul", "value": "Pátio Monte Azul" }, { "label": "Pátio Montes Claros", "value": "Pátio Montes Claros" }, { "label": "Pátio Morro Grande", "value": "Pátio Morro Grande" }, { "label": "Pátio Morro Grande - Cobiça Leopoldina", "value": "Pátio Morro Grande - Cobiça Leopoldina" }, { "label": "Pátio Morro Grande Novo", "value": "Pátio Morro Grande Novo" }, { "label": "Pátio Morro Grande Velho", "value": "Pátio Morro Grande Velho" }, { "label": "Pátio Murundu", "value": "Pátio Murundu" }, { "label": "Pátio Nova Granja", "value": "Pátio Nova Granja" }, { "label": "Pátio Odilon Melo", "value": "Pátio Odilon Melo" }, { "label": "Pátio Oficina de Divinópolis", "value": "Pátio Oficina de Divinópolis" }, { "label": "Pátio Oficina Divinópolis", "value": "Pátio Oficina Divinópolis" }, { "label": "Pátio Oficina Porto Novo", "value": "Pátio Oficina Porto Novo" }, { "label": "Pátio Oliveira", "value": "Pátio Oliveira" }, { "label": "Pátio Órion", "value": "Pátio Órion" }, { "label": "Pátio Orlândia", "value": "Pátio Orlândia" }, { "label": "Pátio Palestina", "value": "Pátio Palestina" }, { "label": "Pátio Parque Industrial", "value": "Pátio Parque Industrial" }, { "label": "Pátio Passa Vinte", "value": "Pátio Passa Vinte" }, { "label": "Pátio Pátio Uberlândia", "value": "Pátio Pátio Uberlândia" }, { "label": "Pátio Pátio Vespasiano", "value": "Pátio Pátio Vespasiano" }, { "label": "Pátio Paulínia", "value": "Pátio Paulínia" }, { "label": "Pátio Paulo Freitas", "value": "Pátio Paulo Freitas" }, { "label": "Pátio Paulo Menicucci", "value": "Pátio Paulo Menicucci" }, { "label": "Pátio Pedro Ferreira", "value": "Pátio Pedro Ferreira" }, { "label": "Pátio Perdões", "value": "Pátio Perdões" }, { "label": "Pátio Pereque", "value": "Pátio Pereque" }, { "label": "Pátio Pirapora", "value": "Pátio Pirapora" }, { "label": "Pátio Piraqueaçu", "value": "Pátio Piraqueaçu" }, { "label": "Pátio Pool", "value": "Pátio Pool" }, { "label": "Pátio Porto Aratu", "value": "Pátio Porto Aratu" }, { "label": "Pátio Porto Novo", "value": "Pátio Porto Novo" }, { "label": "Pátio Porto Santos", "value": "Pátio Porto Santos" }, { "label": "Pátio Porto Velho", "value": "Pátio Porto Velho" }, { "label": "Pátio Posto Arafértil", "value": "Pátio Posto Arafértil" }, { "label": "Pátio Praia Formosa", "value": "Pátio Praia Formosa" }, { "label": "Pátio Prudente de Morais", "value": "Pátio Prudente de Morais" }, { "label": "Pátio Recreio", "value": "Pátio Recreio" }, { "label": "Pátio Replan", "value": "Pátio Replan" }, { "label": "Pátio Reta Fábrica", "value": "Pátio Reta Fábrica" }, { "label": "Pátio Riachuelo", "value": "Pátio Riachuelo" }, { "label": "Pátio Ribeirão Preto", "value": "Pátio Ribeirão Preto" }, { "label": "Pátio Ribeirão Vermelho", "value": "Pátio Ribeirão Vermelho" }, { "label": "Pátio Rio Real", "value": "Pátio Rio Real" }, { "label": "Pátio Rocador Novo", "value": "Pátio Rocador Novo" }, { "label": "Pátio Rocha leão", "value": "Pátio Rocha leão" }, { "label": "Pátio Roncador Novo", "value": "Pátio Roncador Novo" }, { "label": "Pátio S. A. De Pádua", "value": "Pátio S. A. De Pádua" }, { "label": "Pátio Salvador", "value": "Pátio Salvador" }, { "label": "Pátio Santanense", "value": "Pátio Santanense" }, { "label": "Pátio Santo Amaro", "value": "Pátio Santo Amaro" }, { "label": "Pátio Santo Antônio de Pádua", "value": "Pátio Santo Antônio de Pádua" }, { "label": "Pátio Santo Antônio dos Campos ", "value": "Pátio Santo Antônio dos Campos " }, { "label": "Pátio Santo Eduardo", "value": "Pátio Santo Eduardo" }, { "label": "Pátio Santos", "value": "Pátio Santos" }, { "label": "Pátio Santos Dumont", "value": "Pátio Santos Dumont" }, { "label": "Pátio São Francisco", "value": "Pátio São Francisco" }, { "label": "Pátio São João da Boa Vista", "value": "Pátio São João da Boa Vista" }, { "label": "Pátio São Joaquim da Barra", "value": "Pátio São Joaquim da Barra" }, { "label": "Pátio São Simão", "value": "Pátio São Simão" }, { "label": "Pátio Senador Canedo", "value": "Pátio Senador Canedo" }, { "label": "Pátio Senhor do Bonfim", "value": "Pátio Senhor do Bonfim" }, { "label": "Pátio Serrinha", "value": "Pátio Serrinha" }, { "label": "Pátio Sete Lagoas", "value": "Pátio Sete Lagoas" }, { "label": "Pátio Simões Filho", "value": "Pátio Simões Filho" }, { "label": "Pátio Tambaú", "value": "Pátio Tambaú" }, { "label": "Pátio Tamburi", "value": "Pátio Tamburi" }, { "label": "Pátio Tartária", "value": "Pátio Tartária" }, { "label": "Pátio Timboré", "value": "Pátio Timboré" }, { "label": "Pátio Tiplam", "value": "Pátio Tiplam" }, { "label": "Pátio Três Corações", "value": "Pátio Três Corações" }, { "label": "Pátio Três Irmãos", "value": "Pátio Três Irmãos" }, { "label": "Pátio Três Rios", "value": "Pátio Três Rios" }, { "label": "Pátio Tubarão", "value": "Pátio Tubarão" }, { "label": "Pátio Uberaba", "value": "Pátio Uberaba" }, { "label": "Pátio Uberlândia", "value": "Pátio Uberlândia" }, { "label": "Pátio Uruburetama", "value": "Pátio Uruburetama" }, { "label": "Pátio Vai-vem", "value": "Pátio Vai-vem" }, { "label": "Pátio Vale Fértil", "value": "Pátio Vale Fértil" }, { "label": "Pátio Vargem Alta", "value": "Pátio Vargem Alta" }, { "label": "Pátio Varginha", "value": "Pátio Varginha" }, { "label": "Pátio Vespasiano", "value": "Pátio Vespasiano" }, { "label": "Pátio Vianna", "value": "Pátio Vianna" }, { "label": "Pátio Visconde de Itaboraí", "value": "Pátio Visconde de Itaboraí" }, { "label": "Pátio Vitória", "value": "Pátio Vitória" }, { "label": "Pátio Volta Grande", "value": "Pátio Volta Grande" }, { "label": "Pátio Wilson Lobato", "value": "Pátio Wilson Lobato" }, { "label": "Pátio Zelândia", "value": "Pátio Zelândia" }, { "label": "Prefeitura Araguari", "value": "Prefeitura Araguari" }, { "label": "Ramal REPLAN", "value": "Ramal REPLAN" }, { "label": "Terminal de Petróleo Pool", "value": "Terminal de Petróleo Pool" } ];

const XANESG = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const WAGSE = [ { "label": "AC", "value": "AC" }, { "label": "ACB", "value": "ACB" }, { "label": "ACC", "value": "ACC" }, { "label": "ACG", "value": "ACG" }, { "label": "CFG", "value": "CFG" }, { "label": "CNB", "value": "CNB" }, { "label": "CQC", "value": "CQC" }, { "label": "CQD", "value": "CQD" }, { "label": "DC", "value": "DC" }, { "label": "EFE", "value": "EFE" }, { "label": "FBD", "value": "FBD" }, { "label": "FCC ", "value": "FCC " }, { "label": "FEC", "value": "FEC" }, { "label": "FFD", "value": "FFD" }, { "label": "FHC", "value": "FHC" }, { "label": "FHD", "value": "FHD" }, { "label": "FHE", "value": "FHE" }, { "label": "FHR", "value": "FHR" }, { "label": "FLB", "value": "FLB" }, { "label": "FLD", "value": "FLD" }, { "label": "FLE", "value": "FLE" }, { "label": "FMB", "value": "FMB" }, { "label": "FNB", "value": "FNB" }, { "label": "FNC", "value": "FNC" }, { "label": "FOD", "value": "FOD" }, { "label": "FQD", "value": "FQD" }, { "label": "FRB", "value": "FRB" }, { "label": "FRC", "value": "FRC" }, { "label": "FRD", "value": "FRD" }, { "label": "FSB", "value": "FSB" }, { "label": "FSC", "value": "FSC" }, { "label": "FSD", "value": "FSD" }, { "label": "FSQ ", "value": "FSQ " }, { "label": "FTD", "value": "FTD" }, { "label": "GCS", "value": "GCS" }, { "label": "GDD", "value": "GDD" }, { "label": "GDE", "value": "GDE" }, { "label": "GDF", "value": "GDF" }, { "label": "GFC", "value": "GFC" }, { "label": "GFD", "value": "GFD" }, { "label": "GFE", "value": "GFE" }, { "label": "GFR", "value": "GFR" }, { "label": "GG", "value": "GG" }, { "label": "GHC", "value": "GHC" }, { "label": "GHD", "value": "GHD" }, { "label": "GNB", "value": "GNB" }, { "label": "GNC", "value": "GNC" }, { "label": "GND", "value": "GND" }, { "label": "GNT", "value": "GNT" }, { "label": "GOR", "value": "GOR" }, { "label": "GPB", "value": "GPB" }, { "label": "GPD", "value": "GPD" }, { "label": "GQB", "value": "GQB" }, { "label": "GQD", "value": "GQD" }, { "label": "GTC", "value": "GTC" }, { "label": "GTD", "value": "GTD" }, { "label": "HAC", "value": "HAC" }, { "label": "HAD", "value": "HAD" }, { "label": "HED ", "value": "HED " }, { "label": "HEF", "value": "HEF" }, { "label": "HFC", "value": "HFC" }, { "label": "HFD", "value": "HFD" }, { "label": "HFE", "value": "HFE" }, { "label": "HFR ", "value": "HFR " }, { "label": "HFT", "value": "HFT" }, { "label": "HNB", "value": "HNB" }, { "label": "HND", "value": "HND" }, { "label": "HPD", "value": "HPD" }, { "label": "HPE", "value": "HPE" }, { "label": "HTD", "value": "HTD" }, { "label": "Não Informado", "value": "Não Informado" }, { "label": "NLB", "value": "NLB" }, { "label": "PBE", "value": "PBE" }, { "label": "PC", "value": "PC" }, { "label": "PCB", "value": "PCB" }, { "label": "PCD", "value": "PCD" }, { "label": "PDB", "value": "PDB" }, { "label": "PDD", "value": "PDD" }, { "label": "PEB", "value": "PEB" }, { "label": "PEC", "value": "PEC" }, { "label": "PED", "value": "PED" }, { "label": "PEE", "value": "PEE" }, { "label": "PHC", "value": "PHC" }, { "label": "PJC ", "value": "PJC " }, { "label": "PMB", "value": "PMB" }, { "label": "PMC", "value": "PMC" }, { "label": "PME", "value": "PME" }, { "label": "PNB", "value": "PNB" }, { "label": "PNC", "value": "PNC" }, { "label": "PND", "value": "PND" }, { "label": "PQC", "value": "PQC" }, { "label": "PQD", "value": "PQD" }, { "label": "PRC", "value": "PRC" }, { "label": "Q", "value": "Q" }, { "label": "QC", "value": "QC" }, { "label": "QD", "value": "QD" }, { "label": "QNB", "value": "QNB" }, { "label": "QNC", "value": "QNC" }, { "label": "RFC", "value": "RFC" }, { "label": "SC", "value": "SC" }, { "label": "Sucata", "value": "Sucata" }, { "label": "TCB", "value": "TCB" }, { "label": "TCC", "value": "TCC" }, { "label": "TCD", "value": "TCD" }, { "label": "TCE", "value": "TCE" }, { "label": "TCR", "value": "TCR" }, { "label": "TGB", "value": "TGB" }, { "label": "TGD", "value": "TGD" }, { "label": "TNA", "value": "TNA" }, { "label": "TNB", "value": "TNB" }, { "label": "TNC", "value": "TNC" }, { "label": "TND", "value": "TND" }, { "label": "TPC", "value": "TPC" }, { "label": "TPD", "value": "TPD" }, { "label": "TRC", "value": "TRC" }, { "label": "TSB", "value": "TSB" }, { "label": "TSC", "value": "TSC" }, { "label": "TSD", "value": "TSD" }, { "label": "TSE", "value": "TSE" }, { "label": "TSR", "value": "TSR" }, { "label": "TSS", "value": "TSS" } ];

const XTPSTE = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const TPCOB = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const TIPOL = [ { "label": "Abastecimento", "value": "Abastecimento" }, { "label": "Administração", "value": "Administração" }, { "label": "Almoxarifado", "value": "Almoxarifado" }, { "label": "Alojamento", "value": "Alojamento" }, { "label": "Antigo Posto de Conserva", "value": "Antigo Posto de Conserva" }, { "label": "Antigo Posto Médico - Justiça Federal", "value": "Antigo Posto Médico - Justiça Federal" }, { "label": "Antigo Prédio de Segurança do Trabalho", "value": "Antigo Prédio de Segurança do Trabalho" }, { "label": "Areeiro", "value": "Areeiro" }, { "label": "Armazém", "value": "Armazém" }, { "label": "Auditório", "value": "Auditório" }, { "label": "Banheiro", "value": "Banheiro" }, { "label": "Biblioteca Pública", "value": "Biblioteca Pública" }, { "label": "Bilheteria", "value": "Bilheteria" }, { "label": "Brigada de Emergência", "value": "Brigada de Emergência" }, { "label": "Brigada de Incêndio", "value": "Brigada de Incêndio" }, { "label": "Caixa D'Água", "value": "Caixa D'Água" }, { "label": "Câmara Municipal", "value": "Câmara Municipal" }, { "label": "Cantina", "value": "Cantina" }, { "label": "Casa de Bomba", "value": "Casa de Bomba" }, { "label": "Casa de Força", "value": "Casa de Força" }, { "label": "Casa de Máquinas", "value": "Casa de Máquinas" }, { "label": "Cômodo da Bomba", "value": "Cômodo da Bomba" }, { "label": "Cômodo do Compressor", "value": "Cômodo do Compressor" }, { "label": "Cômodo dos Funcionários da Manobra", "value": "Cômodo dos Funcionários da Manobra" }, { "label": "Conserva", "value": "Conserva" }, { "label": "Cozinha", "value": "Cozinha" }, { "label": "Demolido", "value": "Demolido" }, { "label": "Depósito", "value": "Depósito" }, { "label": "Depósito de Areia", "value": "Depósito de Areia" }, { "label": "Depósito de Combustível", "value": "Depósito de Combustível" }, { "label": "Depósito de Ferramentas", "value": "Depósito de Ferramentas" }, { "label": "Eletroeletrônica", "value": "Eletroeletrônica" }, { "label": "Escolinha da Comunidade", "value": "Escolinha da Comunidade" }, { "label": "Escritório", "value": "Escritório" }, { "label": "Escritório da Eletroeletônica", "value": "Escritório da Eletroeletônica" }, { "label": "Escritório da Via Permanente", "value": "Escritório da Via Permanente" }, { "label": "Escritório do Comando Seletivo", "value": "Escritório do Comando Seletivo" }, { "label": "Estação", "value": "Estação" }, { "label": "Estação de Tratamento", "value": "Estação de Tratamento" }, { "label": "Estacionamento de Veículos Rodoviários", "value": "Estacionamento de Veículos Rodoviários" }, { "label": "Galpão", "value": "Galpão" }, { "label": "Garagem", "value": "Garagem" }, { "label": "Garagem de Auto de Linha", "value": "Garagem de Auto de Linha" }, { "label": "Garagem do Auto De Linha", "value": "Garagem do Auto De Linha" }, { "label": "Guarita", "value": "Guarita" }, { "label": "Memorial Moises Vieira Neto", "value": "Memorial Moises Vieira Neto" }, { "label": "Módulo da Eletroeletrônica", "value": "Módulo da Eletroeletrônica" }, { "label": "Módulo da Eletrotécnica", "value": "Módulo da Eletrotécnica" }, { "label": "Moradia", "value": "Moradia" }, { "label": "Museu", "value": "Museu" }, { "label": "Oficina", "value": "Oficina" }, { "label": "Outros", "value": "Outros" }, { "label": "Plataforma", "value": "Plataforma" }, { "label": "Poço", "value": "Poço" }, { "label": "Poço D'Água", "value": "Poço D'Água" }, { "label": "Ponto de encontro", "value": "Ponto de encontro" }, { "label": "Posto da Policia Militar de Minas Gerais", "value": "Posto da Policia Militar de Minas Gerais" }, { "label": "Posto de Abastecimento", "value": "Posto de Abastecimento" }, { "label": "Posto de Telecomunicações", "value": "Posto de Telecomunicações" }, { "label": "Prédio", "value": "Prédio" }, { "label": "Prefeitura", "value": "Prefeitura" }, { "label": "Programa de Erradicação do Trabalho Infantil", "value": "Programa de Erradicação do Trabalho Infantil" }, { "label": "Quadra Esportiva", "value": "Quadra Esportiva" }, { "label": "Refeitório", "value": "Refeitório" }, { "label": "Reservatório", "value": "Reservatório" }, { "label": "Residência", "value": "Residência" }, { "label": "Rotary Club Corinto Centenário", "value": "Rotary Club Corinto Centenário" }, { "label": "Rotunda", "value": "Rotunda" }, { "label": "Sala de Treinamento", "value": "Sala de Treinamento" }, { "label": "Sanitário", "value": "Sanitário" }, { "label": "Sindicato", "value": "Sindicato" }, { "label": "Subestação", "value": "Subestação" }, { "label": "Telégrafo", "value": "Telégrafo" }, { "label": "Torre", "value": "Torre" }, { "label": "Vestiário", "value": "Vestiário" } ];

const TPACR = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" }, { "label": "Outros", "value": "Outros" }, { "label": "Pavimentado", "value": "Pavimentado" }, { "label": "Terra Batida", "value": "Terra Batida" } ];

const TIPES = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const XTPESQ = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const XANSTA = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const SN = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" }, { "label": "Não", "value": "Não" }, { "label": "Sim", "value": "Sim" } ];

const TPPRP = [ { "label": "ARRENDADO", "value": "ARRENDADO" }, { "label": "ARRENDADO - BAIXADO", "value": "ARRENDADO - BAIXADO" }, { "label": "ARRENDADO - DEVOLVIDO", "value": "ARRENDADO - DEVOLVIDO" }, { "label": "ARRENDADO - MRC", "value": "ARRENDADO - MRC" }, { "label": "ARRENDADO - MRC - BAIXADO", "value": "ARRENDADO - MRC - BAIXADO" }, { "label": "ARRENDADO -NÃO CONSTA NA BA", "value": "ARRENDADO -NÃO CONSTA NA BA" }, { "label": "CONSIDERADO ARRENDADO", "value": "CONSIDERADO ARRENDADO" }, { "label": "CONSIDERADO PRÓPRIO", "value": "CONSIDERADO PRÓPRIO" }, { "label": "Não Informado", "value": "Não Informado" }, { "label": "PRÓPRIO", "value": "PRÓPRIO" }, { "label": "PRÓPRIO - BAIXADO ", "value": "PRÓPRIO - BAIXADO " }, { "label": "PRÓPRIO - BAIXADO - MRC", "value": "PRÓPRIO - BAIXADO - MRC" }, { "label": "PRÓPRIO - MRC", "value": "PRÓPRIO - MRC" }, { "label": "PRÓPRIO - NÃO CONSTA NA BA", "value": "PRÓPRIO - NÃO CONSTA NA BA" }, { "label": "SOBRA", "value": "SOBRA" }, { "label": "TERCEIRO", "value": "TERCEIRO" }, { "label": "TERCEIRO - BAIXADO - MRC", "value": "TERCEIRO - BAIXADO - MRC" }, { "label": "TERCEIRO - MRC", "value": "TERCEIRO - MRC" }, { "label": "VALE", "value": "VALE" }, { "label": "VALE - Manut. VLI", "value": "VALE - Manut. VLI" } ];

const RESID = [ { "label": " Leopoldo de Bulhões", "value": " Leopoldo de Bulhões" }, { "label": "Acaiaca", "value": "Acaiaca" }, { "label": "Acajutiba", "value": "Acajutiba" }, { "label": "Água Fria", "value": "Água Fria" }, { "label": "Aguaí", "value": "Aguaí" }, { "label": "Alagoinhas ", "value": "Alagoinhas " }, { "label": "Além Paraíba", "value": "Além Paraíba" }, { "label": "Alfredo Chaves ", "value": "Alfredo Chaves " }, { "label": "Altinópolis", "value": "Altinópolis" }, { "label": "Anápolis", "value": "Anápolis" }, { "label": "Andrelândia", "value": "Andrelândia" }, { "label": "Angra dos Reis", "value": "Angra dos Reis" }, { "label": "Antônio Gonçalves", "value": "Antônio Gonçalves" }, { "label": "Araçai", "value": "Araçai" }, { "label": "Araçaí", "value": "Araçaí" }, { "label": "Aracaju", "value": "Aracaju" }, { "label": "Aracatu", "value": "Aracatu" }, { "label": "Araguari", "value": "Araguari" }, { "label": "Aramari", "value": "Aramari" }, { "label": "Arantina", "value": "Arantina" }, { "label": "Araxá", "value": "Araxá" }, { "label": "Arcos", "value": "Arcos" }, { "label": "Astolfo Dutra", "value": "Astolfo Dutra" }, { "label": "Augusto de Lima", "value": "Augusto de Lima" }, { "label": "Bambuí", "value": "Bambuí" }, { "label": "Barra Longa", "value": "Barra Longa" }, { "label": "Barra Mansa", "value": "Barra Mansa" }, { "label": "Barrocas", "value": "Barrocas" }, { "label": "Belo Horizonte", "value": "Belo Horizonte" }, { "label": "Betim", "value": "Betim" }, { "label": "Bocaiúva", "value": "Bocaiúva" }, { "label": "Bom Sucesso", "value": "Bom Sucesso" }, { "label": "Bonfinópolis", "value": "Bonfinópolis" }, { "label": "Boquim", "value": "Boquim" }, { "label": "Brasília", "value": "Brasília" }, { "label": "Brumado", "value": "Brumado" }, { "label": "Buenópolis", "value": "Buenópolis" }, { "label": "Cachoeira", "value": "Cachoeira" }, { "label": "Cachoeiro de Itapemirim", "value": "Cachoeiro de Itapemirim" }, { "label": "Caculé", "value": "Caculé" }, { "label": "Caldazinha", "value": "Caldazinha" }, { "label": "Caldeirão Grande", "value": "Caldeirão Grande" }, { "label": "Camaçari", "value": "Camaçari" }, { "label": "Cambuci", "value": "Cambuci" }, { "label": "Campinas ", "value": "Campinas " }, { "label": "Campo Belo", "value": "Campo Belo" }, { "label": "Campos Altos", "value": "Campos Altos" }, { "label": "Campos dos Goytacazes", "value": "Campos dos Goytacazes" }, { "label": "Cana Verde", "value": "Cana Verde" }, { "label": "Candeias", "value": "Candeias" }, { "label": "Capitão Enéas", "value": "Capitão Enéas" }, { "label": "Carapebus", "value": "Carapebus" }, { "label": "Carmo da Cachoeira", "value": "Carmo da Cachoeira" }, { "label": "Carmo da Mata", "value": "Carmo da Mata" }, { "label": "Carmo do Cajuru", "value": "Carmo do Cajuru" }, { "label": "Carmo do Cajurú", "value": "Carmo do Cajurú" }, { "label": "Carrancas", "value": "Carrancas" }, { "label": "Casa Branca ", "value": "Casa Branca " }, { "label": "Casemiro de Abreu", "value": "Casemiro de Abreu" }, { "label": "Casimiro de Abreu", "value": "Casimiro de Abreu" }, { "label": "Castro Alves", "value": "Castro Alves" }, { "label": "Catu", "value": "Catu" }, { "label": "Catuti", "value": "Catuti" }, { "label": "Coimbra", "value": "Coimbra" }, { "label": "Conceição da Feira", "value": "Conceição da Feira" }, { "label": "Conceição do Coité", "value": "Conceição do Coité" }, { "label": "Contagem", "value": "Contagem" }, { "label": "Contendas do Sincorá", "value": "Contendas do Sincorá" }, { "label": "Cordisburgo", "value": "Cordisburgo" }, { "label": "Corinto", "value": "Corinto" }, { "label": "Cravinhos", "value": "Cravinhos" }, { "label": "Cruz das Almas", "value": "Cruz das Almas" }, { "label": "Cruzília", "value": "Cruzília" }, { "label": "Cumari", "value": "Cumari" }, { "label": "Curvelo", "value": "Curvelo" }, { "label": "Dias D'Avila", "value": "Dias D'Avila" }, { "label": "Divinópolis", "value": "Divinópolis" }, { "label": "Engenheiro Navarro", "value": "Engenheiro Navarro" }, { "label": "Espinosa", "value": "Espinosa" }, { "label": "Esplanada", "value": "Esplanada" }, { "label": "Estrela do Sul", "value": "Estrela do Sul" }, { "label": "Formiga", "value": "Formiga" }, { "label": "Francisco Sá", "value": "Francisco Sá" }, { "label": "Glaucilândia", "value": "Glaucilândia" }, { "label": "Goiandira", "value": "Goiandira" }, { "label": "Iaçu", "value": "Iaçu" }, { "label": "Ibiá", "value": "Ibiá" }, { "label": "Iguatama", "value": "Iguatama" }, { "label": "Ingaí", "value": "Ingaí" }, { "label": "Ipameri", "value": "Ipameri" }, { "label": "Iraí de Minas", "value": "Iraí de Minas" }, { "label": "Iramaia", "value": "Iramaia" }, { "label": "Itabaianinha", "value": "Itabaianinha" }, { "label": "Itabirito", "value": "Itabirito" }, { "label": "Itapecerica", "value": "Itapecerica" }, { "label": "Itaporanga d'Ajuda", "value": "Itaporanga d'Ajuda" }, { "label": "Itatim", "value": "Itatim" }, { "label": "Itaú de Minas", "value": "Itaú de Minas" }, { "label": "Itaúna", "value": "Itaúna" }, { "label": "Itiúba", "value": "Itiúba" }, { "label": "Itumirim", "value": "Itumirim" }, { "label": "Ituverava", "value": "Ituverava" }, { "label": "Jacaraci", "value": "Jacaraci" }, { "label": "Jaguarari", "value": "Jaguarari" }, { "label": "Janaúba", "value": "Janaúba" }, { "label": "Japaraíba", "value": "Japaraíba" }, { "label": "Japaratuba", "value": "Japaratuba" }, { "label": "Japeri", "value": "Japeri" }, { "label": "Joaquim Felício", "value": "Joaquim Felício" }, { "label": "Juatuba", "value": "Juatuba" }, { "label": "Juazeiro", "value": "Juazeiro" }, { "label": "Lagoa da Prata", "value": "Lagoa da Prata" }, { "label": "Lamarão", "value": "Lamarão" }, { "label": "Lassance", "value": "Lassance" }, { "label": "Lavras", "value": "Lavras" }, { "label": "Leopoldina", "value": "Leopoldina" }, { "label": "Leopoldo Bulhões", "value": "Leopoldo Bulhões" }, { "label": "Liberdade", "value": "Liberdade" }, { "label": "Licínio de Almeida", "value": "Licínio de Almeida" }, { "label": "Luziânia", "value": "Luziânia" }, { "label": "Macaé", "value": "Macaé" }, { "label": "Malhada de Pedras", "value": "Malhada de Pedras" }, { "label": "Marcionílio Souza", "value": "Marcionílio Souza" }, { "label": "Marechal Floriano", "value": "Marechal Floriano" }, { "label": "Mariana", "value": "Mariana" }, { "label": "Mata de São João", "value": "Mata de São João" }, { "label": "Mateus Leme", "value": "Mateus Leme" }, { "label": "Matozinhos", "value": "Matozinhos" }, { "label": "Miguel Pereira", "value": "Miguel Pereira" }, { "label": "Mimoso do Sul", "value": "Mimoso do Sul" }, { "label": "Minduri", "value": "Minduri" }, { "label": "Monte Azul", "value": "Monte Azul" }, { "label": "Montes Claros", "value": "Montes Claros" }, { "label": "Muqui", "value": "Muqui" }, { "label": "Muribeca", "value": "Muribeca" }, { "label": "Muritiba", "value": "Muritiba" }, { "label": "Nepomuceno", "value": "Nepomuceno" }, { "label": "Nova Lima", "value": "Nova Lima" }, { "label": "Nova Ponte", "value": "Nova Ponte" }, { "label": "Oliveira", "value": "Oliveira" }, { "label": "Orizona", "value": "Orizona" }, { "label": "Orlândia", "value": "Orlândia" }, { "label": "Ouriçangas", "value": "Ouriçangas" }, { "label": "Ouro Preto", "value": "Ouro Preto" }, { "label": "Pai Pedro", "value": "Pai Pedro" }, { "label": "Passa Vinte", "value": "Passa Vinte" }, { "label": "Patrocínio", "value": "Patrocínio" }, { "label": "Paty do Alferes", "value": "Paty do Alferes" }, { "label": "Paulínia", "value": "Paulínia" }, { "label": "Pedro Leopoldo", "value": "Pedro Leopoldo" }, { "label": "Perdizes", "value": "Perdizes" }, { "label": "Perdões", "value": "Perdões" }, { "label": "Pirapora", "value": "Pirapora" }, { "label": "Pires do Rio", "value": "Pires do Rio" }, { "label": "Poços de Caldas", "value": "Poços de Caldas" }, { "label": "Pojuca", "value": "Pojuca" }, { "label": "Pontal", "value": "Pontal" }, { "label": "Ponte Nova", "value": "Ponte Nova" }, { "label": "Porteirinha", "value": "Porteirinha" }, { "label": "Pratápolis", "value": "Pratápolis" }, { "label": "Pratinha	", "value": "Pratinha	" }, { "label": "Propriá", "value": "Propriá" }, { "label": "Prudente de Morais", "value": "Prudente de Morais" }, { "label": "Quatis", "value": "Quatis" }, { "label": "Queimadas", "value": "Queimadas" }, { "label": "Raposos", "value": "Raposos" }, { "label": "Recreio", "value": "Recreio" }, { "label": "Riachuelo", "value": "Riachuelo" }, { "label": "Ribeirão Preto", "value": "Ribeirão Preto" }, { "label": "Ribeirão Vermelho", "value": "Ribeirão Vermelho" }, { "label": "Rio Acima", "value": "Rio Acima" }, { "label": "Rio Bonito", "value": "Rio Bonito" }, { "label": "Rio Claro", "value": "Rio Claro" }, { "label": "Rio das Ostras ", "value": "Rio das Ostras " }, { "label": "Rio do Antônio", "value": "Rio do Antônio" }, { "label": "Rio Real", "value": "Rio Real" }, { "label": "Rosário do Catete", "value": "Rosário do Catete" }, { "label": "Sabará", "value": "Sabará" }, { "label": "Salvador", "value": "Salvador" }, { "label": "Santa Juliana", "value": "Santa Juliana" }, { "label": "Santa Luiza", "value": "Santa Luiza" }, { "label": "Santa Luzia", "value": "Santa Luzia" }, { "label": "Santa Rosa de Viterbo", "value": "Santa Rosa de Viterbo" }, { "label": "Santaluz", "value": "Santaluz" }, { "label": "Santo Amaro", "value": "Santo Amaro" }, { "label": "Santo Antônio da Posse", "value": "Santo Antônio da Posse" }, { "label": "Santo Antônio de Pádua", "value": "Santo Antônio de Pádua" }, { "label": "Santo Antônio do Amparo", "value": "Santo Antônio do Amparo" }, { "label": "Santo Antônio do Monte", "value": "Santo Antônio do Monte" }, { "label": "São Cristóvão", "value": "São Cristóvão" }, { "label": "São Félix", "value": "São Félix" }, { "label": "São Fidélis", "value": "São Fidélis" }, { "label": "São Geraldo", "value": "São Geraldo" }, { "label": "São Joaquim da Barra", "value": "São Joaquim da Barra" }, { "label": "São José da Lapa", "value": "São José da Lapa" }, { "label": "São Sebastião do Oeste", "value": "São Sebastião do Oeste" }, { "label": "São Sebastião do Paraíso", "value": "São Sebastião do Paraíso" }, { "label": "São Sebastião do Pas", "value": "São Sebastião do Pas" }, { "label": "São Simão", "value": "São Simão" }, { "label": "São Vicente de Minas", "value": "São Vicente de Minas" }, { "label": "Sapucaia", "value": "Sapucaia" }, { "label": "Senador Canedo", "value": "Senador Canedo" }, { "label": "Senhor do Bonfim", "value": "Senhor do Bonfim" }, { "label": "Serra do Salitre", "value": "Serra do Salitre" }, { "label": "Serrana", "value": "Serrana" }, { "label": "Serrinha", "value": "Serrinha" }, { "label": "Sertãozinho", "value": "Sertãozinho" }, { "label": "Sete Lagoas", "value": "Sete Lagoas" }, { "label": "Silva Jardim", "value": "Silva Jardim" }, { "label": "Silvânia", "value": "Silvânia" }, { "label": "Simões Filho", "value": "Simões Filho" }, { "label": "Tanhaçu", "value": "Tanhaçu" }, { "label": "Tapiraí", "value": "Tapiraí" }, { "label": "Três Corações", "value": "Três Corações" }, { "label": "Três Rios", "value": "Três Rios" }, { "label": "Ubá", "value": "Ubá" }, { "label": "Uberaba", "value": "Uberaba" }, { "label": "Uberlândia", "value": "Uberlândia" }, { "label": "Urandi", "value": "Urandi" }, { "label": "Vargem Alta", "value": "Vargem Alta" }, { "label": "Varginha", "value": "Varginha" }, { "label": "Várzea da Palma", "value": "Várzea da Palma" }, { "label": "Vespasiano", "value": "Vespasiano" }, { "label": "Viana", "value": "Viana" }, { "label": "Vianópolis", "value": "Vianópolis" }, { "label": "Vila Velha", "value": "Vila Velha" }, { "label": "Volta Grande", "value": "Volta Grande" } ];

const TPMED = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const TPEDF = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const XANCOB = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

const RESLC = [
  {"label":"Açominas" ,"value":"Açominas" },
  {"label":"Afonso Arinos" ,"value":"Afonso Arinos" },
  {"label":"Água Branca" ,"value":"Água Branca" },
  {"label":"Agulhas Negras" ,"value":"Agulhas Negras" },
  {"label":"Aiuruoca" ,"value":"Aiuruoca" },
  {"label":"Alberto Flores" ,"value":"Alberto Flores" },
  {"label":"Alça Dupla" ,"value":"Alça Dupla" },
  {"label":"Aliança" ,"value":"Aliança" },
  {"label":"Aljezur" ,"value":"Aljezur" },
  {"label":"Ambaí" ,"value":"Ambaí" },
  {"label":"Andrade Pinto" ,"value":"Andrade Pinto" },
  {"label":"Antonio Carlos" ,"value":"Antonio Carlos" },
  {"label":"Aparecida" ,"value":"Aparecida" },
  {"label":"Aracaré Leste" ,"value":"Aracaré Leste" },
  {"label":"Arantina" ,"value":"Arantina" },
  {"label":"Arará" ,"value":"Arará" },
  {"label":"Areais" ,"value":"Areais" },
  {"label":"Aristides Lobo" ,"value":"Aristides Lobo" },
  {"label":"Arrojado Lisboa" ,"value":"Arrojado Lisboa" },
  {"label":"Baia Sepetiba" ,"value":"Baia Sepetiba" },
  {"label":"Baltazar Fidelis" ,"value":"Baltazar Fidelis" },
  {"label":"Barão de Angra" ,"value":"Barão de Angra" },
  {"label":"Barão de Juparana" ,"value":"Barão de Juparana" },
  {"label":"Barão de Vassouras" ,"value":"Barão de Vassouras" },
  {"label":"Barbacena" ,"value":"Barbacena" },
  {"label":"Bárbara" ,"value":"Bárbara" },
  {"label":"Barnabé" ,"value":"Barnabé" },
  {"label":"Barra do Piraí" ,"value":"Barra do Piraí" },
  {"label":"Barra Funda" ,"value":"Barra Funda" },
  {"label":"Barra Mansa" ,"value":"Barra Mansa" },
  {"label":"Barreiro" ,"value":"Barreiro" },
  {"label":"Barros Filho" ,"value":"Barros Filho" },
  {"label":"Barroso" ,"value":"Barroso" },
  {"label":"Belo Vale" ,"value":"Belo Vale" },
  {"label":"Benfica" ,"value":"Benfica" },
  {"label":"Bom Jardim" ,"value":"Bom Jardim" },
  {"label":"Bom Jardim" ,"value":"Bom Jardim" },
  {"label":"Brás" ,"value":"Brás" },
  {"label":"Brisamar" ,"value":"Brisamar" },
  {"label":"Brumadinho" ,"value":"Brumadinho" },
  {"label":"Buarque de Macedo" ,"value":"Buarque de Macedo" },
  {"label":"Caburu" ,"value":"Caburu" },
  {"label":"Caburu" ,"value":"Caburu" },
  {"label":"Caçapava" ,"value":"Caçapava" },
  {"label":"Cachoeira" ,"value":"Cachoeira" },
  {"label":"Cachoeira da Fumaça" ,"value":"Cachoeira da Fumaça" },
  {"label":"Cachoeira Paulista" ,"value":"Cachoeira Paulista" },
  {"label":"Caetano Lopes" ,"value":"Caetano Lopes" },
  {"label":"Caieiras" ,"value":"Caieiras" },
  {"label":"Calmon Viana" ,"value":"Calmon Viana" },
  {"label":"Campestre" ,"value":"Campestre" },
  {"label":"Campo Grande" ,"value":"Campo Grande" },
  {"label":"Campo Limpo Paulista" ,"value":"Campo Limpo Paulista" },
  {"label":"Capoeira Grande" ,"value":"Capoeira Grande" },
  {"label":"Capuava" ,"value":"Capuava" },
  {"label":"Carandaí" ,"value":"Carandaí" },
  {"label":"Carlos Newlands" ,"value":"Carlos Newlands" },
  {"label":"Carlos Niemeier" ,"value":"Carlos Niemeier" },
  {"label":"Casal" ,"value":"Casal" },
  {"label":"Casal Novo" ,"value":"Casal Novo" },
  {"label":"Cedofeita" ,"value":"Cedofeita" },
  {"label":"Chapeu D´uvas" ,"value":"Chapeu D´uvas" },
  {"label":"Chapeu D'uvas" ,"value":"Chapeu D'uvas" },
  {"label":"Chrockatt de Sá" ,"value":"Chrockatt de Sá" },
  {"label":"Conceiçãozinha" ,"value":"Conceiçãozinha" },
  {"label":"Condutor Castro" ,"value":"Condutor Castro" },
  {"label":"Congonhas do Campo" ,"value":"Congonhas do Campo" },
  {"label":"Congonhas do Campo" ,"value":"Congonhas do Campo" },
  {"label":"Conselheiro Lafaiete" ,"value":"Conselheiro Lafaiete" },
  {"label":"Coroa Grande" ,"value":"Coroa Grande" },
  {"label":"Coronel Araújo" ,"value":"Coronel Araújo" },
  {"label":"Coronel Ermelino Matarazzo" ,"value":"Coronel Ermelino Matarazzo" },
  {"label":"Coronel Eurico" ,"value":"Coronel Eurico" },
  {"label":"Coronel João Carlos Guedes" ,"value":"Coronel João Carlos Guedes" },
  {"label":"Coronel Xavier Chaves" ,"value":"Coronel Xavier Chaves" },
  {"label":"Córrego do Feijão" ,"value":"Córrego do Feijão" },
  {"label":"Córrego Serra" ,"value":"Córrego Serra" },
  {"label":"Costa Barros" ,"value":"Costa Barros" },
  {"label":"Cotegipe" ,"value":"Cotegipe" },
  {"label":"Cruzeiro" ,"value":"Cruzeiro" },
  {"label":"Cubatão" ,"value":"Cubatão" },
  {"label":"Cubatão" ,"value":"Cubatão" },
  {"label":"Curuputuba" ,"value":"Curuputuba" },
  {"label":"Del Castilho" ,"value":"Del Castilho" },
  {"label":"Demétrio Ribeiro" ,"value":"Demétrio Ribeiro" },
  {"label":"Deodoro" ,"value":"Deodoro" },
  {"label":"Dias Tavares" ,"value":"Dias Tavares" },
  {"label":"Doutor Joaquim Murtinho" ,"value":"Doutor Joaquim Murtinho" },
  {"label":"Doutor Joaquim Murtinho" ,"value":"Doutor Joaquim Murtinho" },
  {"label":"Doutor Sá Fortes" ,"value":"Doutor Sá Fortes" },
  {"label":"E.S. Gualberto" ,"value":"E.S. Gualberto" },
  {"label":"Edmar Alves" ,"value":"Edmar Alves" },
  {"label":"Engenheiro Cesar de Souza" ,"value":"Engenheiro Cesar de Souza" },
  {"label":"Engenheiro Drumont" ,"value":"Engenheiro Drumont" },
  {"label":"Engenheiro Eugênio de Melo" ,"value":"Engenheiro Eugênio de Melo" },
  {"label":"Engenheiro Freixinho" ,"value":"Engenheiro Freixinho" },
  {"label":"Engenheiro Gurgel" ,"value":"Engenheiro Gurgel" },
  {"label":"Engenheiro Leonardo Mazziotti" ,"value":"Engenheiro Leonardo Mazziotti" },
  {"label":"Engenheiro Martins Guimarães" ,"value":"Engenheiro Martins Guimarães" },
  {"label":"Engenheiro Neiva" ,"value":"Engenheiro Neiva" },
  {"label":"Engenheiro Passos" ,"value":"Engenheiro Passos" },
  {"label":"Engenheiro Paulo de Frontin" ,"value":"Engenheiro Paulo de Frontin" },
  {"label":"Engenheiro Pedro Paulo" ,"value":"Engenheiro Pedro Paulo" },
  {"label":"Engenheiro São Paulo" ,"value":"Engenheiro São Paulo" },
  {"label":"Engenheiro Simão Tamm" ,"value":"Engenheiro Simão Tamm" },
  {"label":"Engenheiro Taulois" ,"value":"Engenheiro Taulois" },
  {"label":"Engenheiro Vieira Cortez" ,"value":"Engenheiro Vieira Cortez" },
  {"label":"Estação TUF" ,"value":"Estação TUF" },
  {"label":"Ewbanck da Câmara" ,"value":"Ewbanck da Câmara" },
  {"label":"Fernandes Pinheiro" ,"value":"Fernandes Pinheiro" },
  {"label":"Ferrugem" ,"value":"Ferrugem" },
  {"label":"Fim de Trecho" ,"value":"Fim de Trecho" },
  {"label":"Fim do trecho" ,"value":"Fim do trecho" },
  {"label":"Final do trecho" ,"value":"Final do trecho" },
  {"label":"Final Ramal das Fábricas" ,"value":"Final Ramal das Fábricas" },
  {"label":"Floriano" ,"value":"Floriano" },
  {"label":"Francisco Bernardino" ,"value":"Francisco Bernardino" },
  {"label":"Francisco Morato" ,"value":"Francisco Morato" },
  {"label":"Franco da Rocha" ,"value":"Franco da Rocha" },
  {"label":"Furnas" ,"value":"Furnas" },
  {"label":"Gaje" ,"value":"Gaje" },
  {"label":"General Dorival de Brito" ,"value":"General Dorival de Brito" },
  {"label":"Guaíba" ,"value":"Guaíba" },
  {"label":"Guandú" ,"value":"Guandú" },
  {"label":"Guapituba" ,"value":"Guapituba" },
  {"label":"Guararema" ,"value":"Guararema" },
  {"label":"Guaratinguetá" ,"value":"Guaratinguetá" },
  {"label":"Herculano Pena" ,"value":"Herculano Pena" },
  {"label":"Heredia de Sá" ,"value":"Heredia de Sá" },
  {"label":"Honório Gurgel" ,"value":"Honório Gurgel" },
  {"label":"Humberto Antunes" ,"value":"Humberto Antunes" },
  {"label":"Ibicuí" ,"value":"Ibicuí" },
  {"label":"Ibirité" ,"value":"Ibirité" },
  {"label":"Ilídio" ,"value":"Ilídio" },
  {"label":"Inconfidentes" ,"value":"Inconfidentes" },
  {"label":"Inferno Verde" ,"value":"Inferno Verde" },
  {"label":"Ipiranga" ,"value":"Ipiranga" },
  {"label":"Itabirito" ,"value":"Itabirito" },
  {"label":"Itacuruçá" ,"value":"Itacuruçá" },
  {"label":"Itaguaí" ,"value":"Itaguaí" },
  {"label":"Itapeti" ,"value":"Itapeti" },
  {"label":"Itaquaquecetuba" ,"value":"Itaquaquecetuba" },
  {"label":"Itatiaia" ,"value":"Itatiaia" },
  {"label":"Itutinga" ,"value":"Itutinga" },
  {"label":"Jacutinga" ,"value":"Jacutinga" },
  {"label":"Japeri" ,"value":"Japeri" },
  {"label":"Jaraguá" ,"value":"Jaraguá" },
  {"label":"Jatobá" ,"value":"Jatobá" },
  {"label":"Jeceaba" ,"value":"Jeceaba" },
  {"label":"Jeceaba" ,"value":"Jeceaba" },
  {"label":"João Aires" ,"value":"João Aires" },
  {"label":"Joaquim Reis" ,"value":"Joaquim Reis" },
  {"label":"Juiz de Fora" ,"value":"Juiz de Fora" },
  {"label":"KM 10" ,"value":"KM 10" },
  {"label":"KM 110" ,"value":"KM 110" },
  {"label":"KM 5" ,"value":"KM 5" },
  {"label":"KM 6" ,"value":"KM 6" },
  {"label":"KM 7" ,"value":"KM 7" },
  {"label":"KM 8" ,"value":"KM 8" },
  {"label":"KM 9" ,"value":"KM 9" },
  {"label":"Lagoa dos Porcos" ,"value":"Lagoa dos Porcos" },
  {"label":"Lapa" ,"value":"Lapa" },
  {"label":"Lobo Leite" ,"value":"Lobo Leite" },
  {"label":"Lorena" ,"value":"Lorena" },
  {"label":"Luz" ,"value":"Luz" },
  {"label":"Madre de Deus" ,"value":"Madre de Deus" },
  {"label":"Manoel Feio" ,"value":"Manoel Feio" },
  {"label":"Mantiqueira" ,"value":"Mantiqueira" },
  {"label":"Mariano Procópio" ,"value":"Mariano Procópio" },
  {"label":"Mariano Procópio" ,"value":"Mariano Procópio" },
  {"label":"Marinhos" ,"value":"Marinhos" },
  {"label":"Marinhos" ,"value":"Marinhos" },
  {"label":"Mário Belo" ,"value":"Mário Belo" },
  {"label":"Mário Campos" ,"value":"Mário Campos" },
  {"label":"Mário Campos" ,"value":"Mário Campos" },
  {"label":"Mário Castilho" ,"value":"Mário Castilho" },
  {"label":"Martins Costa" ,"value":"Martins Costa" },
  {"label":"Matias Barbosa" ,"value":"Matias Barbosa" },
  {"label":"Mauá" ,"value":"Mauá" },
  {"label":"Melo Franco" ,"value":"Melo Franco" },
  {"label":"Mendes" ,"value":"Mendes" },
  {"label":"Miguel Burnier" ,"value":"Miguel Burnier" },
  {"label":"Moeda" ,"value":"Moeda" },
  {"label":"Mogi das Cruzes" ,"value":"Mogi das Cruzes" },
  {"label":"Mooca" ,"value":"Mooca" },
  {"label":"Morsing" ,"value":"Morsing" },
  {"label":"Olhos D'Água" ,"value":"Olhos D'Água" },
  {"label":"Otavio Dapieve" ,"value":"Otavio Dapieve" },
  {"label":"Ouro Fino" ,"value":"Ouro Fino" },
  {"label":"Ouro Fino" ,"value":"Ouro Fino" },
  {"label":"Pagador Andrade" ,"value":"Pagador Andrade" },
  {"label":"Palmeira da Serra" ,"value":"Palmeira da Serra" },
  {"label":"Paraíba do Sul" ,"value":"Paraíba do Sul" },
  {"label":"Paraibuna" ,"value":"Paraibuna" },
  {"label":"Paraibuna de Metais" ,"value":"Paraibuna de Metais" },
  {"label":"Paraibuna Novo" ,"value":"Paraibuna Novo" },
  {"label":"Paranapiacaba" ,"value":"Paranapiacaba" },
  {"label":"Pari" ,"value":"Pari" },
  {"label":"Pedra do Sino" ,"value":"Pedra do Sino" },
  {"label":"Pedreira de Carandaí" ,"value":"Pedreira de Carandaí" },
  {"label":"Perus" ,"value":"Perus" },
  {"label":"Piaçaguera" ,"value":"Piaçaguera" },
  {"label":"Pindamonhangaba" ,"value":"Pindamonhangaba" },
  {"label":"Pinheiral" ,"value":"Pinheiral" },
  {"label":"Pinheirinho" ,"value":"Pinheirinho" },
  {"label":"Piqueri" ,"value":"Piqueri" },
  {"label":"Pires" ,"value":"Pires" },
  {"label":"Pirituba" ,"value":"Pirituba" },
  {"label":"Pitangueiras" ,"value":"Pitangueiras" },
  {"label":"Pombal" ,"value":"Pombal" },
  {"label":"Pombal" ,"value":"Pombal" },
  {"label":"Porto Real" ,"value":"Porto Real" },
  {"label":"Posto Alfa" ,"value":"Posto Alfa" },
  {"label":"Posto Elisson" ,"value":"Posto Elisson" },
  {"label":"Posto Falcão" ,"value":"Posto Falcão" },
  {"label":"Posto KM 194" ,"value":"Posto KM 194" },
  {"label":"Posto KM 195" ,"value":"Posto KM 195" },
  {"label":"Posto KM 196" ,"value":"Posto KM 196" },
  {"label":"Posto KM 197" ,"value":"Posto KM 197" },
  {"label":"Posto KM 198" ,"value":"Posto KM 198" },
  {"label":"Posto KM 232" ,"value":"Posto KM 232" },
  {"label":"Posto KM 250" ,"value":"Posto KM 250" },
  {"label":"Posto KM 261" ,"value":"Posto KM 261" },
  {"label":"Posto KM 271" ,"value":"Posto KM 271" },
  {"label":"Posto KM 298" ,"value":"Posto KM 298" },
  {"label":"Posto KM 315" ,"value":"Posto KM 315" },
  {"label":"Posto KM 373" ,"value":"Posto KM 373" },
  {"label":"Posto km 374" ,"value":"Posto km 374" },
  {"label":"Posto km 375" ,"value":"Posto km 375" },
  {"label":"Posto km 44" ,"value":"Posto km 44" },
  {"label":"Posto KM 452" ,"value":"Posto KM 452" },
  {"label":"Posto KM 460" ,"value":"Posto KM 460" },
  {"label":"Posto KM 482" ,"value":"Posto KM 482" },
  {"label":"Posto KM 490" ,"value":"Posto KM 490" },
  {"label":"Posto KM 520" ,"value":"Posto KM 520" },
  {"label":"Posto KM 537" ,"value":"Posto KM 537" },
  {"label":"Posto KM 575" ,"value":"Posto KM 575" },
  {"label":"Posto KM 576" ,"value":"Posto KM 576" },
  {"label":"Posto KM 577" ,"value":"Posto KM 577" },
  {"label":"Posto KM 578" ,"value":"Posto KM 578" },
  {"label":"Posto KM 579" ,"value":"Posto KM 579" },
  {"label":"Posto KM 580" ,"value":"Posto KM 580" },
  {"label":"Posto KM 581" ,"value":"Posto KM 581" },
  {"label":"Posto KM 582" ,"value":"Posto KM 582" },
  {"label":"Posto KM 583" ,"value":"Posto KM 583" },
  {"label":"Posto KM 584" ,"value":"Posto KM 584" },
  {"label":"Posto KM 585" ,"value":"Posto KM 585" },
  {"label":"Posto KM 586" ,"value":"Posto KM 586" },
  {"label":"Posto KM 587" ,"value":"Posto KM 587" },
  {"label":"Posto KM 588" ,"value":"Posto KM 588" },
  {"label":"Posto KM 589" ,"value":"Posto KM 589" },
  {"label":"Posto KM 63" ,"value":"Posto KM 63" },
  {"label":"Posto KM 64" ,"value":"Posto KM 64" },
  {"label":"Posto Km 65" ,"value":"Posto Km 65" },
  {"label":"Posto KM315" ,"value":"Posto KM315" },
  {"label":"Prefeito Saladino" ,"value":"Prefeito Saladino" },
  {"label":"Pulverização" ,"value":"Pulverização" },
  {"label":"Queluz" ,"value":"Queluz" },
  {"label":"Rademaker" ,"value":"Rademaker" },
  {"label":"Raiz da Serra" ,"value":"Raiz da Serra" },
  {"label":"Recenvindo" ,"value":"Recenvindo" },
  {"label":"Remédios" ,"value":"Remédios" },
  {"label":"Resende Costa" ,"value":"Resende Costa" },
  {"label":"Retiro" ,"value":"Retiro" },
  {"label":"Ribeirão Pires" ,"value":"Ribeirão Pires" },
  {"label":"Rio Grande da Serra" ,"value":"Rio Grande da Serra" },
  {"label":"Rio Preto" ,"value":"Rio Preto" },
  {"label":"Rio Santana" ,"value":"Rio Santana" },
  {"label":"Rio Vermelho" ,"value":"Rio Vermelho" },
  {"label":"Rio Vermelho" ,"value":"Rio Vermelho" },
  {"label":"Rocha Dias" ,"value":"Rocha Dias" },
  {"label":"Rocha Miranda" ,"value":"Rocha Miranda" },
  {"label":"Rocha Sobrinho" ,"value":"Rocha Sobrinho" },
  {"label":"Roseira" ,"value":"Roseira" },
  {"label":"Saí" ,"value":"Saí" },
  {"label":"Samora Machel" ,"value":"Samora Machel" },
  {"label":"Santa Rosa" ,"value":"Santa Rosa" },
  {"label":"Santa Rosa" ,"value":"Santa Rosa" },
  {"label":"Santana da Barra" ,"value":"Santana da Barra" },
  {"label":"Santo André" ,"value":"Santo André" },
  {"label":"Santos" ,"value":"Santos" },
  {"label":"Santos Dumont" ,"value":"Santos Dumont" },
  {"label":"São Bento" ,"value":"São Bento" },
  {"label":"São Caetano do Sul" ,"value":"São Caetano do Sul" },
  {"label":"São Gonçalo do Bação" ,"value":"São Gonçalo do Bação" },
  {"label":"São Joaquim" ,"value":"São Joaquim" },
  {"label":"São José dos Campos" ,"value":"São José dos Campos" },
  {"label":"São Matheus" ,"value":"São Matheus" },
  {"label":"São Silvestre" ,"value":"São Silvestre" },
  {"label":"Sarzedo" ,"value":"Sarzedo" },
  {"label":"Sarzedo Novo" ,"value":"Sarzedo Novo" },
  {"label":"Saudade" ,"value":"Saudade" },
  {"label":"Sebastião Lacerda" ,"value":"Sebastião Lacerda" },
  {"label":"Serraria" ,"value":"Serraria" },
  {"label":"Sobragi" ,"value":"Sobragi" },
  {"label":"Sobragi" ,"value":"Sobragi" },
  {"label":"Souza Aguiar" ,"value":"Souza Aguiar" },
  {"label":"Suzano" ,"value":"Suzano" },
  {"label":"Suzano" ,"value":"Suzano" },
  {"label":"Suzano Novo" ,"value":"Suzano Novo" },
  {"label":"Tamanduateí" ,"value":"Tamanduateí" },
  {"label":"Taubaté" ,"value":"Taubaté" },
  {"label":"Terminal Cimento Barroso" ,"value":"Terminal Cimento Barroso" },
  {"label":"Três Rios" ,"value":"Três Rios" },
  {"label":"Utinga" ,"value":"Utinga" },
  {"label":"Vargem Alegre" ,"value":"Vargem Alegre" },
  {"label":"Várzea Paulista" ,"value":"Várzea Paulista" },
  {"label":"Viga" ,"value":"Viga" },
  {"label":"Vila Clarice" ,"value":"Vila Clarice" },
  {"label":"Vila Muriqui" ,"value":"Vila Muriqui" },
  {"label":"Vila Queimada" ,"value":"Vila Queimada" },
  {"label":"Volta Redonda" ,"value":"Volta Redonda" },
  {"label":"Waldemar de Brito" ,"value":"Waldemar de Brito" },
];

const XANRVE = [ { "label": "Fora do Escopo", "value": "Fora do Escopo" } ];

module.exports = {
  TPRVI,
  CONSV,
  TIUTI,
  TRCHO,
  COMPN,
  XANEST,
  PMTDT,
  TPOCT,
  XANRVI,
  TPRVE,
  STOPR,
  XANESQ,
  XANSTE,
  CDCRR,
  XTPSTA,
  TPESG,
  CONSG,
  EDPDC,
  CDLMR,
  XANESG,
  WAGSE,
  XTPSTE,
  TPCOB,
  TIPOL,
  TPACR,
  TIPES,
  XTPESQ,
  XANSTA,
  SN,
  TPPRP,
  RESID,
  TPMED,
  TPEDF,
  XANCOB,
  RESLC,
  XANRVE,
};
